//   Ordt 230719.01 autogenerated file 
//   Input: ./rdl_sec_if/test.rdl
//   Parms: ./rdl_sec_if/test.parms
//   Date: Thu Jul 20 13:46:50 EDT 2023
//

#ifndef __BASE_MAP_REGISTER_MAP__
#define __BASE_MAP_REGISTER_MAP__

#include <bits.h>

/* BASE_MAP_REGISTERS memory map */
enum BASE_MAP_REGS {
  BASE_REGS_CONFIG_REGS_0 = 0x0,
  BASE_REGS_CONFIG_REGS_1 = 0x4,
  BASE_REGS_CONFIG_REGS_2 = 0x8,
  BASE_REGS_CONFIG_REGS_3 = 0xc,
  BASE_REGS_CONFIG_REGS_4 = 0x10,
  BASE_REGS_CONFIG_REGS_5 = 0x14,
  BASE_REGS_CONFIG_REGS_6 = 0x18,
  BASE_REGS_CONFIG_REGS_7 = 0x1c,
  PRIMARY_BASE_REGS_CONFIG_REGS_0 = 0x20,
  PRIMARY_BASE_REGS_CONFIG_REGS_1 = 0x24,
  PRIMARY_BASE_REGS_CONFIG_REGS_2 = 0x28,
  PRIMARY_BASE_REGS_CONFIG_REGS_3 = 0x2c,
  PRIMARY_BASE_REGS_CONFIG_REGS_4 = 0x30,
  PRIMARY_BASE_REGS_CONFIG_REGS_5 = 0x34,
  PRIMARY_BASE_REGS_CONFIG_REGS_6 = 0x38,
  PRIMARY_BASE_REGS_CONFIG_REGS_7 = 0x3c
};

/* BASE_REGS_CONFIG_REGS_0 (Config reg set  config_regs_0) register fields */
#define BASE_REGS_CONFIG_REGS_0_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define BASE_REGS_CONFIG_REGS_0_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

/* BASE_REGS_CONFIG_REGS_1 (Config reg set  config_regs_1) register fields */
#define BASE_REGS_CONFIG_REGS_1_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define BASE_REGS_CONFIG_REGS_1_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

/* BASE_REGS_CONFIG_REGS_2 (Config reg set  config_regs_2) register fields */
#define BASE_REGS_CONFIG_REGS_2_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define BASE_REGS_CONFIG_REGS_2_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

/* BASE_REGS_CONFIG_REGS_3 (Config reg set  config_regs_3) register fields */
#define BASE_REGS_CONFIG_REGS_3_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define BASE_REGS_CONFIG_REGS_3_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

/* BASE_REGS_CONFIG_REGS_4 (Config reg set  config_regs_4) register fields */
#define BASE_REGS_CONFIG_REGS_4_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define BASE_REGS_CONFIG_REGS_4_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

/* BASE_REGS_CONFIG_REGS_5 (Config reg set  config_regs_5) register fields */
#define BASE_REGS_CONFIG_REGS_5_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define BASE_REGS_CONFIG_REGS_5_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

/* BASE_REGS_CONFIG_REGS_6 (Config reg set  config_regs_6) register fields */
#define BASE_REGS_CONFIG_REGS_6_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define BASE_REGS_CONFIG_REGS_6_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

/* BASE_REGS_CONFIG_REGS_7 (Config reg set  config_regs_7) register fields */
#define BASE_REGS_CONFIG_REGS_7_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define BASE_REGS_CONFIG_REGS_7_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

/* PRIMARY_BASE_REGS_CONFIG_REGS_0 (Config reg set  config_regs_0) register fields */
#define PRIMARY_BASE_REGS_CONFIG_REGS_0_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define PRIMARY_BASE_REGS_CONFIG_REGS_0_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

/* PRIMARY_BASE_REGS_CONFIG_REGS_1 (Config reg set  config_regs_1) register fields */
#define PRIMARY_BASE_REGS_CONFIG_REGS_1_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define PRIMARY_BASE_REGS_CONFIG_REGS_1_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

/* PRIMARY_BASE_REGS_CONFIG_REGS_2 (Config reg set  config_regs_2) register fields */
#define PRIMARY_BASE_REGS_CONFIG_REGS_2_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define PRIMARY_BASE_REGS_CONFIG_REGS_2_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

/* PRIMARY_BASE_REGS_CONFIG_REGS_3 (Config reg set  config_regs_3) register fields */
#define PRIMARY_BASE_REGS_CONFIG_REGS_3_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define PRIMARY_BASE_REGS_CONFIG_REGS_3_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

/* PRIMARY_BASE_REGS_CONFIG_REGS_4 (Config reg set  config_regs_4) register fields */
#define PRIMARY_BASE_REGS_CONFIG_REGS_4_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define PRIMARY_BASE_REGS_CONFIG_REGS_4_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

/* PRIMARY_BASE_REGS_CONFIG_REGS_5 (Config reg set  config_regs_5) register fields */
#define PRIMARY_BASE_REGS_CONFIG_REGS_5_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define PRIMARY_BASE_REGS_CONFIG_REGS_5_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

/* PRIMARY_BASE_REGS_CONFIG_REGS_6 (Config reg set  config_regs_6) register fields */
#define PRIMARY_BASE_REGS_CONFIG_REGS_6_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define PRIMARY_BASE_REGS_CONFIG_REGS_6_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

/* PRIMARY_BASE_REGS_CONFIG_REGS_7 (Config reg set  config_regs_7) register fields */
#define PRIMARY_BASE_REGS_CONFIG_REGS_7_LSB_FIELD GENMASK(15, 0)    /* Bunch o lsb bits */
#define PRIMARY_BASE_REGS_CONFIG_REGS_7_MSB_FIELD GENMASK(31, 16)    /* Bunch o msb bits */

#endif
