/*   Ordt 170413.03 autogenerated file 
 *   Input: ./rdl_hello/test.rdl
 *   Parms: ./rdl_hello/test.parms
 *   Date: Thu Apr 13 23:28:51 EDT 2017
 */

register_set foo "foo registers" {

  address = 0x0;
  register_width = 32;
  description = "{
    this is a bunch of foo regs bla bla bla
  }";
  register_set bar "bar registers" {
    address = 0x0;
    description = "{
      this is a bunch of bar regs bla bla bla
    }";
    
    register a_reg "a_reg register" {
      address = 0x0;
      repeat = 2;
      nop[16];
      integer fld2[1] "field 2" param {
        access_mode = READ_WRITE;
        reset = unknown;
      };
      nop[5];
      integer fld1[10] "field 1" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
    };
    
    register_set_size = 0x8;
  };
  
  register_set_size = 0x8;
};

