//   Ordt 191120.01 autogenerated file 
//   Input: ./rdl_iwrap/test.rdl
//   Parms: ./rdl_iwrap/test.parms
//   Date: Wed Nov 20 22:21:15 EST 2019
//

//
//---------- module top_jrdl_logic
//
module top_jrdl_logic
(
  clk,
  reset,
  d2l_regs_none_reg_none_w,
  d2l_regs_none_reg_none_we,
  d2l_regs_none_reg_none_re,
  d2l_regs_none_reg_int_w,
  d2l_regs_none_reg_int_we,
  d2l_regs_none_reg_int_re,
  d2l_regs_ext_reg_none_w,
  d2l_regs_ext_reg_none_we,
  d2l_regs_ext_reg_none_re,
  d2l_regs_ext_reg_int_w,
  d2l_regs_ext_reg_int_we,
  d2l_regs_ext_reg_int_re,
  d2l_wrap_info_reg_w,
  d2l_wrap_info_reg_we,
  d2l_wrap_info_reg_re,
  h2l_regs_none_reg_none_fld_none_w,
  h2l_regs_none_reg_none_fld_none_we,
  h2l_regs_none_reg_none_fld_gen_w,
  h2l_regs_none_reg_none_fld_gen_we,
  h2l_regs_none_reg_none_fld_ext_w,
  h2l_regs_none_reg_none_fld_ext_we,
  h2l_regs_none_reg_none_fld_int_w,
  h2l_regs_none_reg_none_fld_int_we,
  h2l_regs_none_reg_int_fld_none_w,
  h2l_regs_none_reg_int_fld_none_we,
  h2l_regs_none_reg_int_fld_gen_w,
  h2l_regs_none_reg_int_fld_gen_we,
  h2l_regs_none_reg_int_fld_ext_w,
  h2l_regs_none_reg_int_fld_ext_we,
  h2l_regs_none_reg_int_fld_int_w,
  h2l_regs_none_reg_int_fld_int_we,
  h2l_regs_ext_reg_none_fld_none_w,
  h2l_regs_ext_reg_none_fld_none_we,
  h2l_regs_ext_reg_none_fld_gen_w,
  h2l_regs_ext_reg_none_fld_gen_we,
  h2l_regs_ext_reg_none_fld_ext_w,
  h2l_regs_ext_reg_none_fld_ext_we,
  h2l_regs_ext_reg_none_fld_int_w,
  h2l_regs_ext_reg_none_fld_int_we,
  h2l_regs_ext_reg_int_fld_none_w,
  h2l_regs_ext_reg_int_fld_none_we,
  h2l_regs_ext_reg_int_fld_gen_w,
  h2l_regs_ext_reg_int_fld_gen_we,
  h2l_regs_ext_reg_int_fld_ext_w,
  h2l_regs_ext_reg_int_fld_ext_we,
  h2l_regs_ext_reg_int_fld_int_w,
  h2l_regs_ext_reg_int_fld_int_we,

  l2d_regs_none_reg_none_r,
  l2d_regs_none_reg_int_r,
  l2d_regs_ext_reg_none_r,
  l2d_regs_ext_reg_int_r,
  l2d_wrap_info_reg_r,
  l2h_regs_none_reg_none_fld_none_r,
  l2h_regs_none_reg_none_fld_gen_r,
  l2h_regs_none_reg_none_fld_ext_r,
  l2h_regs_none_reg_none_fld_int_r,
  l2h_regs_none_reg_int_fld_none_r,
  l2h_regs_none_reg_int_fld_gen_r,
  l2h_regs_none_reg_int_fld_ext_r,
  l2h_regs_none_reg_int_fld_int_r,
  l2h_regs_ext_reg_none_fld_none_r,
  l2h_regs_ext_reg_none_fld_gen_r,
  l2h_regs_ext_reg_none_fld_ext_r,
  l2h_regs_ext_reg_none_fld_int_r,
  l2h_regs_ext_reg_int_fld_none_r,
  l2h_regs_ext_reg_int_fld_gen_r,
  l2h_regs_ext_reg_int_fld_ext_r,
  l2h_regs_ext_reg_int_fld_int_r,
  l2h_wrap_info_reg_bar1_r,
  l2h_wrap_info_reg_bar2_r,
  l2h_wrap_info_reg_bar3_r );

  //------- inputs
  input    clk;
  input    reset;
  input     [31:0] d2l_regs_none_reg_none_w;
  input    d2l_regs_none_reg_none_we;
  input    d2l_regs_none_reg_none_re;
  input     [31:0] d2l_regs_none_reg_int_w;
  input    d2l_regs_none_reg_int_we;
  input    d2l_regs_none_reg_int_re;
  input     [31:0] d2l_regs_ext_reg_none_w;
  input    d2l_regs_ext_reg_none_we;
  input    d2l_regs_ext_reg_none_re;
  input     [31:0] d2l_regs_ext_reg_int_w;
  input    d2l_regs_ext_reg_int_we;
  input    d2l_regs_ext_reg_int_re;
  input     [31:0] d2l_wrap_info_reg_w;
  input    d2l_wrap_info_reg_we;
  input    d2l_wrap_info_reg_re;
  input    h2l_regs_none_reg_none_fld_none_w;
  input    h2l_regs_none_reg_none_fld_none_we;
  input    h2l_regs_none_reg_none_fld_gen_w;
  input    h2l_regs_none_reg_none_fld_gen_we;
  input    h2l_regs_none_reg_none_fld_ext_w;
  input    h2l_regs_none_reg_none_fld_ext_we;
  input    h2l_regs_none_reg_none_fld_int_w;
  input    h2l_regs_none_reg_none_fld_int_we;
  input    h2l_regs_none_reg_int_fld_none_w;
  input    h2l_regs_none_reg_int_fld_none_we;
  input    h2l_regs_none_reg_int_fld_gen_w;
  input    h2l_regs_none_reg_int_fld_gen_we;
  input    h2l_regs_none_reg_int_fld_ext_w;
  input    h2l_regs_none_reg_int_fld_ext_we;
  input    h2l_regs_none_reg_int_fld_int_w;
  input    h2l_regs_none_reg_int_fld_int_we;
  input    h2l_regs_ext_reg_none_fld_none_w;
  input    h2l_regs_ext_reg_none_fld_none_we;
  input    h2l_regs_ext_reg_none_fld_gen_w;
  input    h2l_regs_ext_reg_none_fld_gen_we;
  input    h2l_regs_ext_reg_none_fld_ext_w;
  input    h2l_regs_ext_reg_none_fld_ext_we;
  input    h2l_regs_ext_reg_none_fld_int_w;
  input    h2l_regs_ext_reg_none_fld_int_we;
  input    h2l_regs_ext_reg_int_fld_none_w;
  input    h2l_regs_ext_reg_int_fld_none_we;
  input    h2l_regs_ext_reg_int_fld_gen_w;
  input    h2l_regs_ext_reg_int_fld_gen_we;
  input    h2l_regs_ext_reg_int_fld_ext_w;
  input    h2l_regs_ext_reg_int_fld_ext_we;
  input    h2l_regs_ext_reg_int_fld_int_w;
  input    h2l_regs_ext_reg_int_fld_int_we;

  //------- outputs
  output     [31:0] l2d_regs_none_reg_none_r;
  output     [31:0] l2d_regs_none_reg_int_r;
  output     [31:0] l2d_regs_ext_reg_none_r;
  output     [31:0] l2d_regs_ext_reg_int_r;
  output     [31:0] l2d_wrap_info_reg_r;
  output    l2h_regs_none_reg_none_fld_none_r;
  output    l2h_regs_none_reg_none_fld_gen_r;
  output    l2h_regs_none_reg_none_fld_ext_r;
  output    l2h_regs_none_reg_none_fld_int_r;
  output    l2h_regs_none_reg_int_fld_none_r;
  output    l2h_regs_none_reg_int_fld_gen_r;
  output    l2h_regs_none_reg_int_fld_ext_r;
  output    l2h_regs_none_reg_int_fld_int_r;
  output    l2h_regs_ext_reg_none_fld_none_r;
  output    l2h_regs_ext_reg_none_fld_gen_r;
  output    l2h_regs_ext_reg_none_fld_ext_r;
  output    l2h_regs_ext_reg_none_fld_int_r;
  output    l2h_regs_ext_reg_int_fld_none_r;
  output    l2h_regs_ext_reg_int_fld_gen_r;
  output    l2h_regs_ext_reg_int_fld_ext_r;
  output    l2h_regs_ext_reg_int_fld_int_r;
  output    l2h_wrap_info_reg_bar1_r;
  output    l2h_wrap_info_reg_bar2_r;
  output    l2h_wrap_info_reg_bar3_r;


  //------- reg defines
  reg  rg_regs_none_reg_none_fld_none;
  reg  reg_regs_none_reg_none_fld_none_next;
  reg  l2h_regs_none_reg_none_fld_none_r;
  reg  rg_regs_none_reg_none_fld_gen;
  reg  reg_regs_none_reg_none_fld_gen_next;
  reg  l2h_regs_none_reg_none_fld_gen_r;
  reg  rg_regs_none_reg_none_fld_ext;
  reg  reg_regs_none_reg_none_fld_ext_next;
  reg  l2h_regs_none_reg_none_fld_ext_r;
  reg  rg_regs_none_reg_none_fld_int;
  reg  reg_regs_none_reg_none_fld_int_next;
  reg  l2h_regs_none_reg_none_fld_int_r;
  reg   [31:0] l2d_regs_none_reg_none_r;
  reg  rg_regs_none_reg_int_fld_none;
  reg  reg_regs_none_reg_int_fld_none_next;
  reg  l2h_regs_none_reg_int_fld_none_r;
  reg  rg_regs_none_reg_int_fld_gen;
  reg  reg_regs_none_reg_int_fld_gen_next;
  reg  l2h_regs_none_reg_int_fld_gen_r;
  reg  rg_regs_none_reg_int_fld_ext;
  reg  reg_regs_none_reg_int_fld_ext_next;
  reg  l2h_regs_none_reg_int_fld_ext_r;
  reg  rg_regs_none_reg_int_fld_int;
  reg  reg_regs_none_reg_int_fld_int_next;
  reg  l2h_regs_none_reg_int_fld_int_r;
  reg   [31:0] l2d_regs_none_reg_int_r;
  reg  rg_regs_ext_reg_none_fld_none;
  reg  reg_regs_ext_reg_none_fld_none_next;
  reg  l2h_regs_ext_reg_none_fld_none_r;
  reg  rg_regs_ext_reg_none_fld_gen;
  reg  reg_regs_ext_reg_none_fld_gen_next;
  reg  l2h_regs_ext_reg_none_fld_gen_r;
  reg  rg_regs_ext_reg_none_fld_ext;
  reg  reg_regs_ext_reg_none_fld_ext_next;
  reg  l2h_regs_ext_reg_none_fld_ext_r;
  reg  rg_regs_ext_reg_none_fld_int;
  reg  reg_regs_ext_reg_none_fld_int_next;
  reg  l2h_regs_ext_reg_none_fld_int_r;
  reg   [31:0] l2d_regs_ext_reg_none_r;
  reg  rg_regs_ext_reg_int_fld_none;
  reg  reg_regs_ext_reg_int_fld_none_next;
  reg  l2h_regs_ext_reg_int_fld_none_r;
  reg  rg_regs_ext_reg_int_fld_gen;
  reg  reg_regs_ext_reg_int_fld_gen_next;
  reg  l2h_regs_ext_reg_int_fld_gen_r;
  reg  rg_regs_ext_reg_int_fld_ext;
  reg  reg_regs_ext_reg_int_fld_ext_next;
  reg  l2h_regs_ext_reg_int_fld_ext_r;
  reg  rg_regs_ext_reg_int_fld_int;
  reg  reg_regs_ext_reg_int_fld_int_next;
  reg  l2h_regs_ext_reg_int_fld_int_r;
  reg   [31:0] l2d_regs_ext_reg_int_r;
  reg  rg_wrap_info_reg_bar1;
  reg  reg_wrap_info_reg_bar1_next;
  reg  l2h_wrap_info_reg_bar1_r;
  reg  rg_wrap_info_reg_bar2;
  reg  reg_wrap_info_reg_bar2_next;
  reg  l2h_wrap_info_reg_bar2_r;
  reg  rg_wrap_info_reg_bar3;
  reg  reg_wrap_info_reg_bar3_next;
  reg  l2h_wrap_info_reg_bar3_r;
  reg   [31:0] l2d_wrap_info_reg_r;
  
  
  //------- combinatorial assigns for regs_none_reg_none (pio read data)
  always @ (*) begin
    l2d_regs_none_reg_none_r = 32'b0;
    l2d_regs_none_reg_none_r [0]  = rg_regs_none_reg_none_fld_none;
    l2d_regs_none_reg_none_r [1]  = rg_regs_none_reg_none_fld_gen;
    l2d_regs_none_reg_none_r [2]  = rg_regs_none_reg_none_fld_ext;
    l2d_regs_none_reg_none_r [3]  = rg_regs_none_reg_none_fld_int;
  end
  
  //------- combinatorial assigns for regs_none_reg_int
  always @ (*) begin
    reg_regs_none_reg_int_fld_none_next = rg_regs_none_reg_int_fld_none;
    l2h_regs_none_reg_int_fld_none_r = rg_regs_none_reg_int_fld_none;
    reg_regs_none_reg_int_fld_gen_next = rg_regs_none_reg_int_fld_gen;
    l2h_regs_none_reg_int_fld_gen_r = rg_regs_none_reg_int_fld_gen;
    reg_regs_none_reg_int_fld_ext_next = rg_regs_none_reg_int_fld_ext;
    l2h_regs_none_reg_int_fld_ext_r = rg_regs_none_reg_int_fld_ext;
    reg_regs_none_reg_int_fld_int_next = rg_regs_none_reg_int_fld_int;
    l2h_regs_none_reg_int_fld_int_r = rg_regs_none_reg_int_fld_int;
    if (h2l_regs_none_reg_int_fld_none_we) reg_regs_none_reg_int_fld_none_next = h2l_regs_none_reg_int_fld_none_w;
    if (h2l_regs_none_reg_int_fld_gen_we) reg_regs_none_reg_int_fld_gen_next = h2l_regs_none_reg_int_fld_gen_w;
    if (h2l_regs_none_reg_int_fld_ext_we) reg_regs_none_reg_int_fld_ext_next = h2l_regs_none_reg_int_fld_ext_w;
    if (h2l_regs_none_reg_int_fld_int_we) reg_regs_none_reg_int_fld_int_next = h2l_regs_none_reg_int_fld_int_w;
    if (d2l_regs_none_reg_int_we) reg_regs_none_reg_int_fld_none_next = d2l_regs_none_reg_int_w [0] ;
    if (d2l_regs_none_reg_int_we) reg_regs_none_reg_int_fld_gen_next = d2l_regs_none_reg_int_w [1] ;
    if (d2l_regs_none_reg_int_we) reg_regs_none_reg_int_fld_ext_next = d2l_regs_none_reg_int_w [2] ;
    if (d2l_regs_none_reg_int_we) reg_regs_none_reg_int_fld_int_next = d2l_regs_none_reg_int_w [3] ;
  end
  
  //------- reg assigns for regs_none_reg_int
  always @ (posedge clk) begin
    if (reset) begin
      rg_regs_none_reg_int_fld_none <= #1 1'b0;
      rg_regs_none_reg_int_fld_gen <= #1 1'b0;
      rg_regs_none_reg_int_fld_ext <= #1 1'b0;
      rg_regs_none_reg_int_fld_int <= #1 1'b0;
    end
    else begin
      rg_regs_none_reg_int_fld_none <= #1  reg_regs_none_reg_int_fld_none_next;
      rg_regs_none_reg_int_fld_gen <= #1  reg_regs_none_reg_int_fld_gen_next;
      rg_regs_none_reg_int_fld_ext <= #1  reg_regs_none_reg_int_fld_ext_next;
      rg_regs_none_reg_int_fld_int <= #1  reg_regs_none_reg_int_fld_int_next;
    end
  end
  
  //------- combinatorial assigns for regs_none_reg_none
  always @ (*) begin
    reg_regs_none_reg_none_fld_none_next = rg_regs_none_reg_none_fld_none;
    l2h_regs_none_reg_none_fld_none_r = rg_regs_none_reg_none_fld_none;
    reg_regs_none_reg_none_fld_gen_next = rg_regs_none_reg_none_fld_gen;
    l2h_regs_none_reg_none_fld_gen_r = rg_regs_none_reg_none_fld_gen;
    reg_regs_none_reg_none_fld_ext_next = rg_regs_none_reg_none_fld_ext;
    l2h_regs_none_reg_none_fld_ext_r = rg_regs_none_reg_none_fld_ext;
    reg_regs_none_reg_none_fld_int_next = rg_regs_none_reg_none_fld_int;
    l2h_regs_none_reg_none_fld_int_r = rg_regs_none_reg_none_fld_int;
    if (h2l_regs_none_reg_none_fld_none_we) reg_regs_none_reg_none_fld_none_next = h2l_regs_none_reg_none_fld_none_w;
    if (h2l_regs_none_reg_none_fld_gen_we) reg_regs_none_reg_none_fld_gen_next = h2l_regs_none_reg_none_fld_gen_w;
    if (h2l_regs_none_reg_none_fld_ext_we) reg_regs_none_reg_none_fld_ext_next = h2l_regs_none_reg_none_fld_ext_w;
    if (h2l_regs_none_reg_none_fld_int_we) reg_regs_none_reg_none_fld_int_next = h2l_regs_none_reg_none_fld_int_w;
    if (d2l_regs_none_reg_none_we) reg_regs_none_reg_none_fld_none_next = d2l_regs_none_reg_none_w [0] ;
    if (d2l_regs_none_reg_none_we) reg_regs_none_reg_none_fld_gen_next = d2l_regs_none_reg_none_w [1] ;
    if (d2l_regs_none_reg_none_we) reg_regs_none_reg_none_fld_ext_next = d2l_regs_none_reg_none_w [2] ;
    if (d2l_regs_none_reg_none_we) reg_regs_none_reg_none_fld_int_next = d2l_regs_none_reg_none_w [3] ;
  end
  
  //------- reg assigns for regs_none_reg_none
  always @ (posedge clk) begin
    if (reset) begin
      rg_regs_none_reg_none_fld_none <= #1 1'b0;
      rg_regs_none_reg_none_fld_gen <= #1 1'b0;
      rg_regs_none_reg_none_fld_ext <= #1 1'b0;
      rg_regs_none_reg_none_fld_int <= #1 1'b0;
    end
    else begin
      rg_regs_none_reg_none_fld_none <= #1  reg_regs_none_reg_none_fld_none_next;
      rg_regs_none_reg_none_fld_gen <= #1  reg_regs_none_reg_none_fld_gen_next;
      rg_regs_none_reg_none_fld_ext <= #1  reg_regs_none_reg_none_fld_ext_next;
      rg_regs_none_reg_none_fld_int <= #1  reg_regs_none_reg_none_fld_int_next;
    end
  end
  
  //------- combinatorial assigns for wrap_info_reg (pio read data)
  always @ (*) begin
    l2d_wrap_info_reg_r = 32'b0;
    l2d_wrap_info_reg_r [0]  = rg_wrap_info_reg_bar1;
    l2d_wrap_info_reg_r [1]  = rg_wrap_info_reg_bar2;
    l2d_wrap_info_reg_r [2]  = rg_wrap_info_reg_bar3;
  end
  
  //------- combinatorial assigns for regs_ext_reg_none (pio read data)
  always @ (*) begin
    l2d_regs_ext_reg_none_r = 32'b0;
    l2d_regs_ext_reg_none_r [0]  = rg_regs_ext_reg_none_fld_none;
    l2d_regs_ext_reg_none_r [1]  = rg_regs_ext_reg_none_fld_gen;
    l2d_regs_ext_reg_none_r [2]  = rg_regs_ext_reg_none_fld_ext;
    l2d_regs_ext_reg_none_r [3]  = rg_regs_ext_reg_none_fld_int;
  end
  
  //------- combinatorial assigns for wrap_info_reg
  always @ (*) begin
    reg_wrap_info_reg_bar1_next = rg_wrap_info_reg_bar1;
    l2h_wrap_info_reg_bar1_r = rg_wrap_info_reg_bar1;
    reg_wrap_info_reg_bar2_next = rg_wrap_info_reg_bar2;
    l2h_wrap_info_reg_bar2_r = rg_wrap_info_reg_bar2;
    reg_wrap_info_reg_bar3_next = rg_wrap_info_reg_bar3;
    l2h_wrap_info_reg_bar3_r = rg_wrap_info_reg_bar3;
    if (d2l_wrap_info_reg_we) reg_wrap_info_reg_bar1_next = d2l_wrap_info_reg_w [0] ;
    if (d2l_wrap_info_reg_we) reg_wrap_info_reg_bar2_next = d2l_wrap_info_reg_w [1] ;
    if (d2l_wrap_info_reg_we) reg_wrap_info_reg_bar3_next = d2l_wrap_info_reg_w [2] ;
  end
  
  //------- reg assigns for wrap_info_reg
  always @ (posedge clk) begin
    if (reset) begin
      rg_wrap_info_reg_bar1 <= #1 1'b0;
      rg_wrap_info_reg_bar2 <= #1 1'b0;
      rg_wrap_info_reg_bar3 <= #1 1'b0;
    end
    else begin
      rg_wrap_info_reg_bar1 <= #1  reg_wrap_info_reg_bar1_next;
      rg_wrap_info_reg_bar2 <= #1  reg_wrap_info_reg_bar2_next;
      rg_wrap_info_reg_bar3 <= #1  reg_wrap_info_reg_bar3_next;
    end
  end
  
  //------- combinatorial assigns for regs_ext_reg_int (pio read data)
  always @ (*) begin
    l2d_regs_ext_reg_int_r = 32'b0;
    l2d_regs_ext_reg_int_r [0]  = rg_regs_ext_reg_int_fld_none;
    l2d_regs_ext_reg_int_r [1]  = rg_regs_ext_reg_int_fld_gen;
    l2d_regs_ext_reg_int_r [2]  = rg_regs_ext_reg_int_fld_ext;
    l2d_regs_ext_reg_int_r [3]  = rg_regs_ext_reg_int_fld_int;
  end
  
  //------- combinatorial assigns for regs_none_reg_int (pio read data)
  always @ (*) begin
    l2d_regs_none_reg_int_r = 32'b0;
    l2d_regs_none_reg_int_r [0]  = rg_regs_none_reg_int_fld_none;
    l2d_regs_none_reg_int_r [1]  = rg_regs_none_reg_int_fld_gen;
    l2d_regs_none_reg_int_r [2]  = rg_regs_none_reg_int_fld_ext;
    l2d_regs_none_reg_int_r [3]  = rg_regs_none_reg_int_fld_int;
  end
  
  //------- combinatorial assigns for regs_ext_reg_none
  always @ (*) begin
    reg_regs_ext_reg_none_fld_none_next = rg_regs_ext_reg_none_fld_none;
    l2h_regs_ext_reg_none_fld_none_r = rg_regs_ext_reg_none_fld_none;
    reg_regs_ext_reg_none_fld_gen_next = rg_regs_ext_reg_none_fld_gen;
    l2h_regs_ext_reg_none_fld_gen_r = rg_regs_ext_reg_none_fld_gen;
    reg_regs_ext_reg_none_fld_ext_next = rg_regs_ext_reg_none_fld_ext;
    l2h_regs_ext_reg_none_fld_ext_r = rg_regs_ext_reg_none_fld_ext;
    reg_regs_ext_reg_none_fld_int_next = rg_regs_ext_reg_none_fld_int;
    l2h_regs_ext_reg_none_fld_int_r = rg_regs_ext_reg_none_fld_int;
    if (h2l_regs_ext_reg_none_fld_none_we) reg_regs_ext_reg_none_fld_none_next = h2l_regs_ext_reg_none_fld_none_w;
    if (h2l_regs_ext_reg_none_fld_gen_we) reg_regs_ext_reg_none_fld_gen_next = h2l_regs_ext_reg_none_fld_gen_w;
    if (h2l_regs_ext_reg_none_fld_ext_we) reg_regs_ext_reg_none_fld_ext_next = h2l_regs_ext_reg_none_fld_ext_w;
    if (h2l_regs_ext_reg_none_fld_int_we) reg_regs_ext_reg_none_fld_int_next = h2l_regs_ext_reg_none_fld_int_w;
    if (d2l_regs_ext_reg_none_we) reg_regs_ext_reg_none_fld_none_next = d2l_regs_ext_reg_none_w [0] ;
    if (d2l_regs_ext_reg_none_we) reg_regs_ext_reg_none_fld_gen_next = d2l_regs_ext_reg_none_w [1] ;
    if (d2l_regs_ext_reg_none_we) reg_regs_ext_reg_none_fld_ext_next = d2l_regs_ext_reg_none_w [2] ;
    if (d2l_regs_ext_reg_none_we) reg_regs_ext_reg_none_fld_int_next = d2l_regs_ext_reg_none_w [3] ;
  end
  
  //------- reg assigns for regs_ext_reg_none
  always @ (posedge clk) begin
    if (reset) begin
      rg_regs_ext_reg_none_fld_none <= #1 1'b0;
      rg_regs_ext_reg_none_fld_gen <= #1 1'b0;
      rg_regs_ext_reg_none_fld_ext <= #1 1'b0;
      rg_regs_ext_reg_none_fld_int <= #1 1'b0;
    end
    else begin
      rg_regs_ext_reg_none_fld_none <= #1  reg_regs_ext_reg_none_fld_none_next;
      rg_regs_ext_reg_none_fld_gen <= #1  reg_regs_ext_reg_none_fld_gen_next;
      rg_regs_ext_reg_none_fld_ext <= #1  reg_regs_ext_reg_none_fld_ext_next;
      rg_regs_ext_reg_none_fld_int <= #1  reg_regs_ext_reg_none_fld_int_next;
    end
  end
  
  //------- combinatorial assigns for regs_ext_reg_int
  always @ (*) begin
    reg_regs_ext_reg_int_fld_none_next = rg_regs_ext_reg_int_fld_none;
    l2h_regs_ext_reg_int_fld_none_r = rg_regs_ext_reg_int_fld_none;
    reg_regs_ext_reg_int_fld_gen_next = rg_regs_ext_reg_int_fld_gen;
    l2h_regs_ext_reg_int_fld_gen_r = rg_regs_ext_reg_int_fld_gen;
    reg_regs_ext_reg_int_fld_ext_next = rg_regs_ext_reg_int_fld_ext;
    l2h_regs_ext_reg_int_fld_ext_r = rg_regs_ext_reg_int_fld_ext;
    reg_regs_ext_reg_int_fld_int_next = rg_regs_ext_reg_int_fld_int;
    l2h_regs_ext_reg_int_fld_int_r = rg_regs_ext_reg_int_fld_int;
    if (h2l_regs_ext_reg_int_fld_none_we) reg_regs_ext_reg_int_fld_none_next = h2l_regs_ext_reg_int_fld_none_w;
    if (h2l_regs_ext_reg_int_fld_gen_we) reg_regs_ext_reg_int_fld_gen_next = h2l_regs_ext_reg_int_fld_gen_w;
    if (h2l_regs_ext_reg_int_fld_ext_we) reg_regs_ext_reg_int_fld_ext_next = h2l_regs_ext_reg_int_fld_ext_w;
    if (h2l_regs_ext_reg_int_fld_int_we) reg_regs_ext_reg_int_fld_int_next = h2l_regs_ext_reg_int_fld_int_w;
    if (d2l_regs_ext_reg_int_we) reg_regs_ext_reg_int_fld_none_next = d2l_regs_ext_reg_int_w [0] ;
    if (d2l_regs_ext_reg_int_we) reg_regs_ext_reg_int_fld_gen_next = d2l_regs_ext_reg_int_w [1] ;
    if (d2l_regs_ext_reg_int_we) reg_regs_ext_reg_int_fld_ext_next = d2l_regs_ext_reg_int_w [2] ;
    if (d2l_regs_ext_reg_int_we) reg_regs_ext_reg_int_fld_int_next = d2l_regs_ext_reg_int_w [3] ;
  end
  
  //------- reg assigns for regs_ext_reg_int
  always @ (posedge clk) begin
    if (reset) begin
      rg_regs_ext_reg_int_fld_none <= #1 1'b0;
      rg_regs_ext_reg_int_fld_gen <= #1 1'b0;
      rg_regs_ext_reg_int_fld_ext <= #1 1'b0;
      rg_regs_ext_reg_int_fld_int <= #1 1'b0;
    end
    else begin
      rg_regs_ext_reg_int_fld_none <= #1  reg_regs_ext_reg_int_fld_none_next;
      rg_regs_ext_reg_int_fld_gen <= #1  reg_regs_ext_reg_int_fld_gen_next;
      rg_regs_ext_reg_int_fld_ext <= #1  reg_regs_ext_reg_int_fld_ext_next;
      rg_regs_ext_reg_int_fld_int <= #1  reg_regs_ext_reg_int_fld_int_next;
    end
  end
  
endmodule

//
//---------- module top_jrdl_decode
//
module top_jrdl_decode
(
  clk,
  reset,
  leaf_dec_wr_data,
  leaf_dec_addr,
  leaf_dec_block_sel,
  leaf_dec_valid,
  leaf_dec_wr_dvld,
  leaf_dec_cycle,
  leaf_dec_wr_width,
  l2d_regs_none_reg_none_r,
  l2d_regs_none_reg_int_r,
  l2d_regs_ext_reg_none_r,
  l2d_regs_ext_reg_int_r,
  l2d_wrap_info_reg_r,

  dec_leaf_rd_data,
  dec_leaf_ack,
  dec_leaf_nack,
  dec_leaf_accept,
  dec_leaf_reject,
  dec_leaf_retry_atomic,
  dec_leaf_data_width,
  d2l_regs_none_reg_none_w,
  d2l_regs_none_reg_none_we,
  d2l_regs_none_reg_none_re,
  d2l_regs_none_reg_int_w,
  d2l_regs_none_reg_int_we,
  d2l_regs_none_reg_int_re,
  d2l_regs_ext_reg_none_w,
  d2l_regs_ext_reg_none_we,
  d2l_regs_ext_reg_none_re,
  d2l_regs_ext_reg_int_w,
  d2l_regs_ext_reg_int_we,
  d2l_regs_ext_reg_int_re,
  d2l_wrap_info_reg_w,
  d2l_wrap_info_reg_we,
  d2l_wrap_info_reg_re );

  //------- inputs
  input    clk;
  input    reset;
  input     [31:0] leaf_dec_wr_data;
  input     [39:0] leaf_dec_addr;
  input    leaf_dec_block_sel;
  input    leaf_dec_valid;
  input    leaf_dec_wr_dvld;
  input     [1:0] leaf_dec_cycle;
  input     [2:0] leaf_dec_wr_width;
  input     [31:0] l2d_regs_none_reg_none_r;
  input     [31:0] l2d_regs_none_reg_int_r;
  input     [31:0] l2d_regs_ext_reg_none_r;
  input     [31:0] l2d_regs_ext_reg_int_r;
  input     [31:0] l2d_wrap_info_reg_r;

  //------- outputs
  output     [31:0] dec_leaf_rd_data;
  output    dec_leaf_ack;
  output    dec_leaf_nack;
  output    dec_leaf_accept;
  output    dec_leaf_reject;
  output    dec_leaf_retry_atomic;
  output     [2:0] dec_leaf_data_width;
  output     [31:0] d2l_regs_none_reg_none_w;
  output    d2l_regs_none_reg_none_we;
  output    d2l_regs_none_reg_none_re;
  output     [31:0] d2l_regs_none_reg_int_w;
  output    d2l_regs_none_reg_int_we;
  output    d2l_regs_none_reg_int_re;
  output     [31:0] d2l_regs_ext_reg_none_w;
  output    d2l_regs_ext_reg_none_we;
  output    d2l_regs_ext_reg_none_re;
  output     [31:0] d2l_regs_ext_reg_int_w;
  output    d2l_regs_ext_reg_int_we;
  output    d2l_regs_ext_reg_int_re;
  output     [31:0] d2l_wrap_info_reg_w;
  output    d2l_wrap_info_reg_we;
  output    d2l_wrap_info_reg_re;


  //------- wire defines
  wire   [31:0] pio_dec_write_data;
  wire   [9:2] pio_dec_address;
  wire  pio_dec_read;
  wire  pio_dec_write;
  wire   [39:0] block_sel_addr;
  wire  block_sel;
  wire  leaf_dec_valid_active;
  wire  leaf_dec_wr_dvld_active;
  
  //------- reg defines
  reg   [31:0] d2l_regs_none_reg_none_w;
  reg  d2l_regs_none_reg_none_we;
  reg  d2l_regs_none_reg_none_re;
  reg   [31:0] d2l_regs_none_reg_int_w;
  reg  d2l_regs_none_reg_int_we;
  reg  d2l_regs_none_reg_int_re;
  reg   [31:0] d2l_regs_ext_reg_none_w;
  reg  d2l_regs_ext_reg_none_we;
  reg  d2l_regs_ext_reg_none_re;
  reg   [31:0] d2l_regs_ext_reg_int_w;
  reg  d2l_regs_ext_reg_int_we;
  reg  d2l_regs_ext_reg_int_re;
  reg   [31:0] d2l_wrap_info_reg_w;
  reg  d2l_wrap_info_reg_we;
  reg  d2l_wrap_info_reg_re;
  reg  leaf_dec_valid_hld1;
  reg  leaf_dec_valid_hld1_next;
  reg  leaf_dec_wr_dvld_hld1;
  reg  leaf_dec_wr_dvld_hld1_next;
  reg  pio_write_active;
  reg  pio_read_active;
  reg   [9:2] pio_dec_address_d1;
  reg   [31:0] pio_dec_write_data_d1;
  reg   [31:0] dec_pio_read_data;
  reg   [31:0] dec_pio_read_data_d1;
  reg  dec_pio_ack;
  reg  dec_pio_nack;
  reg  dec_pio_ack_next;
  reg  dec_pio_nack_next;
  reg  pio_internal_ack;
  reg  pio_internal_nack;
  reg  pio_external_ack;
  reg  pio_external_nack;
  reg  pio_external_ack_next;
  reg  pio_external_nack_next;
  reg  pio_no_acks;
  reg  pio_activate_write;
  reg  pio_activate_read;
  reg   [31:0] dec_pio_read_data_next;
  reg  external_transaction_active;
  
  
  //------- assigns
  assign  pio_dec_write_data = leaf_dec_wr_data;
  assign  dec_leaf_rd_data = dec_pio_read_data;
  assign  dec_leaf_ack = dec_pio_ack;
  assign  dec_leaf_nack = dec_pio_nack;
  assign  pio_dec_address = leaf_dec_addr [9:2] ;
  assign  block_sel_addr = 40'h0;
  assign  block_sel = leaf_dec_block_sel;
  assign  leaf_dec_wr_dvld_active = leaf_dec_wr_dvld | leaf_dec_wr_dvld_hld1;
  assign  leaf_dec_valid_active = leaf_dec_valid | leaf_dec_valid_hld1;
  assign  dec_leaf_accept = leaf_dec_valid & block_sel;
  assign  dec_leaf_reject = leaf_dec_valid & ~block_sel;
  assign  pio_dec_read = block_sel & leaf_dec_valid_active & (leaf_dec_cycle == 2'b10);
  assign  pio_dec_write = block_sel & leaf_dec_wr_dvld_active & (leaf_dec_cycle[1] == 1'b0);
  assign  dec_leaf_retry_atomic = 1'b0;
  assign  dec_leaf_data_width = 3'b0;
  
  //------- combinatorial assigns for pio read data
  always @ (*) begin
    dec_pio_read_data = dec_pio_read_data_d1;
  end
  
  //------- reg assigns for pio read data
  always @ (posedge clk) begin
    if (reset) begin
      dec_pio_read_data_d1 <= #1  32'b0;
    end
    else begin
      dec_pio_read_data_d1 <= #1 dec_pio_read_data_next;
    end
  end
  
  //------- reg assigns for pio i/f
  always @ (posedge clk) begin
    if (reset) begin
      pio_write_active <= #1  1'b0;
      pio_read_active <= #1  1'b0;
    end
    else begin
      pio_write_active <= #1  pio_write_active ? pio_no_acks : pio_activate_write;
      pio_read_active <= #1  pio_read_active ? pio_no_acks : pio_activate_read;
    end
    pio_dec_address_d1 <= #1   pio_dec_address;
    pio_dec_write_data_d1 <= #1  pio_dec_write_data;
  end
  
  //------- combinatorial assigns for leaf i/f
  always @ (*) begin
    leaf_dec_valid_hld1_next = leaf_dec_valid | leaf_dec_valid_hld1;
    if (dec_pio_ack_next | dec_pio_nack_next) leaf_dec_valid_hld1_next = 1'b0;
    leaf_dec_wr_dvld_hld1_next = leaf_dec_wr_dvld | leaf_dec_wr_dvld_hld1;
    if (dec_pio_ack_next | dec_pio_nack_next | leaf_dec_valid) leaf_dec_wr_dvld_hld1_next = 1'b0;
  end
  
  //------- reg assigns for leaf i/f
  always @ (posedge clk) begin
    if (reset) begin
      leaf_dec_valid_hld1 <= #1  1'b0;
      leaf_dec_wr_dvld_hld1 <= #1  1'b0;
    end
    else begin
      leaf_dec_valid_hld1 <= #1 leaf_dec_valid_hld1_next;
      leaf_dec_wr_dvld_hld1 <= #1 leaf_dec_wr_dvld_hld1_next;
    end
  end
  
  //------- combinatorial assigns for pio ack/nack
  always @ (*) begin
    pio_internal_nack = (pio_read_active | pio_write_active) & ~pio_internal_ack & ~external_transaction_active;
    dec_pio_ack_next = (pio_internal_ack | (pio_external_ack_next & external_transaction_active));
    dec_pio_nack_next = (pio_internal_nack | (pio_external_nack_next & external_transaction_active));
    pio_no_acks = ~(dec_pio_ack | dec_pio_nack | pio_external_ack | pio_external_nack);
    pio_activate_write = (pio_dec_write & ~(dec_pio_ack | dec_pio_nack));
    pio_activate_read = (pio_dec_read & ~(dec_pio_ack | dec_pio_nack));
  end
  
  //------- reg assigns for pio ack/nack
  always @ (posedge clk) begin
    if (reset) begin
      dec_pio_ack <= #1 1'b0;
      dec_pio_nack <= #1 1'b0;
      pio_external_ack <= #1  1'b0;
      pio_external_nack <= #1  1'b0;
    end
    else begin
      dec_pio_ack <= #1 dec_pio_ack ? 1'b0 : dec_pio_ack_next;
      dec_pio_nack <= #1 dec_pio_nack ? 1'b0 : dec_pio_nack_next;
      pio_external_ack <= #1 pio_external_ack_next;
      pio_external_nack <= #1 pio_external_nack_next;
    end
  end
  
  
  //------- address decode
  always @ (*) begin
    pio_internal_ack = 1'b0;
    external_transaction_active = 1'b0;
    pio_external_ack_next = 1'b0;
    pio_external_nack_next = 1'b0;
    dec_pio_read_data_next = 32'b0;
    
    d2l_regs_none_reg_none_w = pio_dec_write_data_d1  [31:0] ;
    d2l_regs_none_reg_none_we = 1'b0;
    d2l_regs_none_reg_none_re = 1'b0;
    d2l_regs_none_reg_int_w = pio_dec_write_data_d1  [31:0] ;
    d2l_regs_none_reg_int_we = 1'b0;
    d2l_regs_none_reg_int_re = 1'b0;
    d2l_regs_ext_reg_none_w = pio_dec_write_data_d1  [31:0] ;
    d2l_regs_ext_reg_none_we = 1'b0;
    d2l_regs_ext_reg_none_re = 1'b0;
    d2l_regs_ext_reg_int_w = pio_dec_write_data_d1  [31:0] ;
    d2l_regs_ext_reg_int_we = 1'b0;
    d2l_regs_ext_reg_int_re = 1'b0;
    d2l_wrap_info_reg_w = pio_dec_write_data_d1  [31:0] ;
    d2l_wrap_info_reg_we = 1'b0;
    d2l_wrap_info_reg_re = 1'b0;
    
    casez(pio_dec_address_d1)
    //  Register: regs_none.reg_none     Address: 0x0     External: false
    8'b00000000:
      begin
        d2l_regs_none_reg_none_we = pio_write_active & ~dec_pio_ack;
        d2l_regs_none_reg_none_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_regs_none_reg_none_r;
      end
    //  Register: regs_none.reg_int     Address: 0x4     External: false
    8'b00000001:
      begin
        d2l_regs_none_reg_int_we = pio_write_active & ~dec_pio_ack;
        d2l_regs_none_reg_int_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_regs_none_reg_int_r;
      end
    //  Register: regs_ext.reg_none     Address: 0x8     External: false
    8'b00000010:
      begin
        d2l_regs_ext_reg_none_we = pio_write_active & ~dec_pio_ack;
        d2l_regs_ext_reg_none_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_regs_ext_reg_none_r;
      end
    //  Register: regs_ext.reg_int     Address: 0xc     External: false
    8'b00000011:
      begin
        d2l_regs_ext_reg_int_we = pio_write_active & ~dec_pio_ack;
        d2l_regs_ext_reg_int_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_regs_ext_reg_int_r;
      end
    //  Register: wrap_info_reg     Address: 0x200     External: false
    8'b10000000:
      begin
        d2l_wrap_info_reg_we = pio_write_active & ~dec_pio_ack;
        d2l_wrap_info_reg_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_wrap_info_reg_r;
      end
    endcase
  end
  
endmodule

//
//---------- module top_pio
//
module top_pio
(
  clk,
  reset,
  h2l_regs_none_reg_none_fld_none_w,
  h2l_regs_none_reg_none_fld_none_we,
  h2l_regs_none_reg_none_fld_gen_w,
  h2l_regs_none_reg_none_fld_gen_we,
  h2l_regs_none_reg_none_fld_ext_w,
  h2l_regs_none_reg_none_fld_ext_we,
  h2l_regs_none_reg_none_fld_int_w,
  h2l_regs_none_reg_none_fld_int_we,
  h2l_regs_none_reg_int_fld_none_w,
  h2l_regs_none_reg_int_fld_none_we,
  h2l_regs_none_reg_int_fld_gen_w,
  h2l_regs_none_reg_int_fld_gen_we,
  h2l_regs_none_reg_int_fld_ext_w,
  h2l_regs_none_reg_int_fld_ext_we,
  h2l_regs_none_reg_int_fld_int_w,
  h2l_regs_none_reg_int_fld_int_we,
  h2l_regs_ext_reg_none_fld_none_w,
  h2l_regs_ext_reg_none_fld_none_we,
  h2l_regs_ext_reg_none_fld_gen_w,
  h2l_regs_ext_reg_none_fld_gen_we,
  h2l_regs_ext_reg_none_fld_ext_w,
  h2l_regs_ext_reg_none_fld_ext_we,
  h2l_regs_ext_reg_none_fld_int_w,
  h2l_regs_ext_reg_none_fld_int_we,
  h2l_regs_ext_reg_int_fld_none_w,
  h2l_regs_ext_reg_int_fld_none_we,
  h2l_regs_ext_reg_int_fld_gen_w,
  h2l_regs_ext_reg_int_fld_gen_we,
  h2l_regs_ext_reg_int_fld_ext_w,
  h2l_regs_ext_reg_int_fld_ext_we,
  h2l_regs_ext_reg_int_fld_int_w,
  h2l_regs_ext_reg_int_fld_int_we,
  leaf_dec_wr_data,
  leaf_dec_addr,
  leaf_dec_block_sel,
  leaf_dec_valid,
  leaf_dec_wr_dvld,
  leaf_dec_cycle,
  leaf_dec_wr_width,

  l2h_regs_none_reg_none_fld_none_r,
  l2h_regs_none_reg_none_fld_gen_r,
  l2h_regs_none_reg_none_fld_ext_r,
  l2h_regs_none_reg_none_fld_int_r,
  l2h_regs_none_reg_int_fld_none_r,
  l2h_regs_none_reg_int_fld_gen_r,
  l2h_regs_none_reg_int_fld_ext_r,
  l2h_regs_none_reg_int_fld_int_r,
  l2h_regs_ext_reg_none_fld_none_r,
  l2h_regs_ext_reg_none_fld_gen_r,
  l2h_regs_ext_reg_none_fld_ext_r,
  l2h_regs_ext_reg_none_fld_int_r,
  l2h_regs_ext_reg_int_fld_none_r,
  l2h_regs_ext_reg_int_fld_gen_r,
  l2h_regs_ext_reg_int_fld_ext_r,
  l2h_regs_ext_reg_int_fld_int_r,
  l2h_wrap_info_reg_bar1_r,
  l2h_wrap_info_reg_bar2_r,
  l2h_wrap_info_reg_bar3_r,
  dec_leaf_rd_data,
  dec_leaf_ack,
  dec_leaf_nack,
  dec_leaf_accept,
  dec_leaf_reject,
  dec_leaf_retry_atomic,
  dec_leaf_data_width );

  //------- inputs
  input    clk;
  input    reset;
  input    h2l_regs_none_reg_none_fld_none_w;
  input    h2l_regs_none_reg_none_fld_none_we;
  input    h2l_regs_none_reg_none_fld_gen_w;
  input    h2l_regs_none_reg_none_fld_gen_we;
  input    h2l_regs_none_reg_none_fld_ext_w;
  input    h2l_regs_none_reg_none_fld_ext_we;
  input    h2l_regs_none_reg_none_fld_int_w;
  input    h2l_regs_none_reg_none_fld_int_we;
  input    h2l_regs_none_reg_int_fld_none_w;
  input    h2l_regs_none_reg_int_fld_none_we;
  input    h2l_regs_none_reg_int_fld_gen_w;
  input    h2l_regs_none_reg_int_fld_gen_we;
  input    h2l_regs_none_reg_int_fld_ext_w;
  input    h2l_regs_none_reg_int_fld_ext_we;
  input    h2l_regs_none_reg_int_fld_int_w;
  input    h2l_regs_none_reg_int_fld_int_we;
  input    h2l_regs_ext_reg_none_fld_none_w;
  input    h2l_regs_ext_reg_none_fld_none_we;
  input    h2l_regs_ext_reg_none_fld_gen_w;
  input    h2l_regs_ext_reg_none_fld_gen_we;
  input    h2l_regs_ext_reg_none_fld_ext_w;
  input    h2l_regs_ext_reg_none_fld_ext_we;
  input    h2l_regs_ext_reg_none_fld_int_w;
  input    h2l_regs_ext_reg_none_fld_int_we;
  input    h2l_regs_ext_reg_int_fld_none_w;
  input    h2l_regs_ext_reg_int_fld_none_we;
  input    h2l_regs_ext_reg_int_fld_gen_w;
  input    h2l_regs_ext_reg_int_fld_gen_we;
  input    h2l_regs_ext_reg_int_fld_ext_w;
  input    h2l_regs_ext_reg_int_fld_ext_we;
  input    h2l_regs_ext_reg_int_fld_int_w;
  input    h2l_regs_ext_reg_int_fld_int_we;
  input     [31:0] leaf_dec_wr_data;
  input     [39:0] leaf_dec_addr;
  input    leaf_dec_block_sel;
  input    leaf_dec_valid;
  input    leaf_dec_wr_dvld;
  input     [1:0] leaf_dec_cycle;
  input     [2:0] leaf_dec_wr_width;

  //------- outputs
  output    l2h_regs_none_reg_none_fld_none_r;
  output    l2h_regs_none_reg_none_fld_gen_r;
  output    l2h_regs_none_reg_none_fld_ext_r;
  output    l2h_regs_none_reg_none_fld_int_r;
  output    l2h_regs_none_reg_int_fld_none_r;
  output    l2h_regs_none_reg_int_fld_gen_r;
  output    l2h_regs_none_reg_int_fld_ext_r;
  output    l2h_regs_none_reg_int_fld_int_r;
  output    l2h_regs_ext_reg_none_fld_none_r;
  output    l2h_regs_ext_reg_none_fld_gen_r;
  output    l2h_regs_ext_reg_none_fld_ext_r;
  output    l2h_regs_ext_reg_none_fld_int_r;
  output    l2h_regs_ext_reg_int_fld_none_r;
  output    l2h_regs_ext_reg_int_fld_gen_r;
  output    l2h_regs_ext_reg_int_fld_ext_r;
  output    l2h_regs_ext_reg_int_fld_int_r;
  output    l2h_wrap_info_reg_bar1_r;
  output    l2h_wrap_info_reg_bar2_r;
  output    l2h_wrap_info_reg_bar3_r;
  output     [31:0] dec_leaf_rd_data;
  output    dec_leaf_ack;
  output    dec_leaf_nack;
  output    dec_leaf_accept;
  output    dec_leaf_reject;
  output    dec_leaf_retry_atomic;
  output     [2:0] dec_leaf_data_width;


  //------- wire defines
  wire   [31:0] d2l_regs_none_reg_none_w;
  wire  d2l_regs_none_reg_none_we;
  wire  d2l_regs_none_reg_none_re;
  wire   [31:0] d2l_regs_none_reg_int_w;
  wire  d2l_regs_none_reg_int_we;
  wire  d2l_regs_none_reg_int_re;
  wire   [31:0] d2l_regs_ext_reg_none_w;
  wire  d2l_regs_ext_reg_none_we;
  wire  d2l_regs_ext_reg_none_re;
  wire   [31:0] d2l_regs_ext_reg_int_w;
  wire  d2l_regs_ext_reg_int_we;
  wire  d2l_regs_ext_reg_int_re;
  wire   [31:0] d2l_wrap_info_reg_w;
  wire  d2l_wrap_info_reg_we;
  wire  d2l_wrap_info_reg_re;
  wire   [31:0] l2d_regs_none_reg_none_r;
  wire   [31:0] l2d_regs_none_reg_int_r;
  wire   [31:0] l2d_regs_ext_reg_none_r;
  wire   [31:0] l2d_regs_ext_reg_int_r;
  wire   [31:0] l2d_wrap_info_reg_r;
  
  
  top_jrdl_decode pio_decode (
    .clk(clk),
    .reset(reset),
    .leaf_dec_wr_data(leaf_dec_wr_data),
    .leaf_dec_addr(leaf_dec_addr),
    .leaf_dec_block_sel(leaf_dec_block_sel),
    .leaf_dec_valid(leaf_dec_valid),
    .leaf_dec_wr_dvld(leaf_dec_wr_dvld),
    .leaf_dec_cycle(leaf_dec_cycle),
    .leaf_dec_wr_width(leaf_dec_wr_width),
    .l2d_regs_none_reg_none_r(l2d_regs_none_reg_none_r),
    .l2d_regs_none_reg_int_r(l2d_regs_none_reg_int_r),
    .l2d_regs_ext_reg_none_r(l2d_regs_ext_reg_none_r),
    .l2d_regs_ext_reg_int_r(l2d_regs_ext_reg_int_r),
    .l2d_wrap_info_reg_r(l2d_wrap_info_reg_r),
    .dec_leaf_rd_data(dec_leaf_rd_data),
    .dec_leaf_ack(dec_leaf_ack),
    .dec_leaf_nack(dec_leaf_nack),
    .dec_leaf_accept(dec_leaf_accept),
    .dec_leaf_reject(dec_leaf_reject),
    .dec_leaf_retry_atomic(dec_leaf_retry_atomic),
    .dec_leaf_data_width(dec_leaf_data_width),
    .d2l_regs_none_reg_none_w(d2l_regs_none_reg_none_w),
    .d2l_regs_none_reg_none_we(d2l_regs_none_reg_none_we),
    .d2l_regs_none_reg_none_re(d2l_regs_none_reg_none_re),
    .d2l_regs_none_reg_int_w(d2l_regs_none_reg_int_w),
    .d2l_regs_none_reg_int_we(d2l_regs_none_reg_int_we),
    .d2l_regs_none_reg_int_re(d2l_regs_none_reg_int_re),
    .d2l_regs_ext_reg_none_w(d2l_regs_ext_reg_none_w),
    .d2l_regs_ext_reg_none_we(d2l_regs_ext_reg_none_we),
    .d2l_regs_ext_reg_none_re(d2l_regs_ext_reg_none_re),
    .d2l_regs_ext_reg_int_w(d2l_regs_ext_reg_int_w),
    .d2l_regs_ext_reg_int_we(d2l_regs_ext_reg_int_we),
    .d2l_regs_ext_reg_int_re(d2l_regs_ext_reg_int_re),
    .d2l_wrap_info_reg_w(d2l_wrap_info_reg_w),
    .d2l_wrap_info_reg_we(d2l_wrap_info_reg_we),
    .d2l_wrap_info_reg_re(d2l_wrap_info_reg_re) );
    
  top_jrdl_logic pio_logic (
    .clk(clk),
    .reset(reset),
    .d2l_regs_none_reg_none_w(d2l_regs_none_reg_none_w),
    .d2l_regs_none_reg_none_we(d2l_regs_none_reg_none_we),
    .d2l_regs_none_reg_none_re(d2l_regs_none_reg_none_re),
    .d2l_regs_none_reg_int_w(d2l_regs_none_reg_int_w),
    .d2l_regs_none_reg_int_we(d2l_regs_none_reg_int_we),
    .d2l_regs_none_reg_int_re(d2l_regs_none_reg_int_re),
    .d2l_regs_ext_reg_none_w(d2l_regs_ext_reg_none_w),
    .d2l_regs_ext_reg_none_we(d2l_regs_ext_reg_none_we),
    .d2l_regs_ext_reg_none_re(d2l_regs_ext_reg_none_re),
    .d2l_regs_ext_reg_int_w(d2l_regs_ext_reg_int_w),
    .d2l_regs_ext_reg_int_we(d2l_regs_ext_reg_int_we),
    .d2l_regs_ext_reg_int_re(d2l_regs_ext_reg_int_re),
    .d2l_wrap_info_reg_w(d2l_wrap_info_reg_w),
    .d2l_wrap_info_reg_we(d2l_wrap_info_reg_we),
    .d2l_wrap_info_reg_re(d2l_wrap_info_reg_re),
    .h2l_regs_none_reg_none_fld_none_w(h2l_regs_none_reg_none_fld_none_w),
    .h2l_regs_none_reg_none_fld_none_we(h2l_regs_none_reg_none_fld_none_we),
    .h2l_regs_none_reg_none_fld_gen_w(h2l_regs_none_reg_none_fld_gen_w),
    .h2l_regs_none_reg_none_fld_gen_we(h2l_regs_none_reg_none_fld_gen_we),
    .h2l_regs_none_reg_none_fld_ext_w(h2l_regs_none_reg_none_fld_ext_w),
    .h2l_regs_none_reg_none_fld_ext_we(h2l_regs_none_reg_none_fld_ext_we),
    .h2l_regs_none_reg_none_fld_int_w(h2l_regs_none_reg_none_fld_int_w),
    .h2l_regs_none_reg_none_fld_int_we(h2l_regs_none_reg_none_fld_int_we),
    .h2l_regs_none_reg_int_fld_none_w(h2l_regs_none_reg_int_fld_none_w),
    .h2l_regs_none_reg_int_fld_none_we(h2l_regs_none_reg_int_fld_none_we),
    .h2l_regs_none_reg_int_fld_gen_w(h2l_regs_none_reg_int_fld_gen_w),
    .h2l_regs_none_reg_int_fld_gen_we(h2l_regs_none_reg_int_fld_gen_we),
    .h2l_regs_none_reg_int_fld_ext_w(h2l_regs_none_reg_int_fld_ext_w),
    .h2l_regs_none_reg_int_fld_ext_we(h2l_regs_none_reg_int_fld_ext_we),
    .h2l_regs_none_reg_int_fld_int_w(h2l_regs_none_reg_int_fld_int_w),
    .h2l_regs_none_reg_int_fld_int_we(h2l_regs_none_reg_int_fld_int_we),
    .h2l_regs_ext_reg_none_fld_none_w(h2l_regs_ext_reg_none_fld_none_w),
    .h2l_regs_ext_reg_none_fld_none_we(h2l_regs_ext_reg_none_fld_none_we),
    .h2l_regs_ext_reg_none_fld_gen_w(h2l_regs_ext_reg_none_fld_gen_w),
    .h2l_regs_ext_reg_none_fld_gen_we(h2l_regs_ext_reg_none_fld_gen_we),
    .h2l_regs_ext_reg_none_fld_ext_w(h2l_regs_ext_reg_none_fld_ext_w),
    .h2l_regs_ext_reg_none_fld_ext_we(h2l_regs_ext_reg_none_fld_ext_we),
    .h2l_regs_ext_reg_none_fld_int_w(h2l_regs_ext_reg_none_fld_int_w),
    .h2l_regs_ext_reg_none_fld_int_we(h2l_regs_ext_reg_none_fld_int_we),
    .h2l_regs_ext_reg_int_fld_none_w(h2l_regs_ext_reg_int_fld_none_w),
    .h2l_regs_ext_reg_int_fld_none_we(h2l_regs_ext_reg_int_fld_none_we),
    .h2l_regs_ext_reg_int_fld_gen_w(h2l_regs_ext_reg_int_fld_gen_w),
    .h2l_regs_ext_reg_int_fld_gen_we(h2l_regs_ext_reg_int_fld_gen_we),
    .h2l_regs_ext_reg_int_fld_ext_w(h2l_regs_ext_reg_int_fld_ext_w),
    .h2l_regs_ext_reg_int_fld_ext_we(h2l_regs_ext_reg_int_fld_ext_we),
    .h2l_regs_ext_reg_int_fld_int_w(h2l_regs_ext_reg_int_fld_int_w),
    .h2l_regs_ext_reg_int_fld_int_we(h2l_regs_ext_reg_int_fld_int_we),
    .l2d_regs_none_reg_none_r(l2d_regs_none_reg_none_r),
    .l2d_regs_none_reg_int_r(l2d_regs_none_reg_int_r),
    .l2d_regs_ext_reg_none_r(l2d_regs_ext_reg_none_r),
    .l2d_regs_ext_reg_int_r(l2d_regs_ext_reg_int_r),
    .l2d_wrap_info_reg_r(l2d_wrap_info_reg_r),
    .l2h_regs_none_reg_none_fld_none_r(l2h_regs_none_reg_none_fld_none_r),
    .l2h_regs_none_reg_none_fld_gen_r(l2h_regs_none_reg_none_fld_gen_r),
    .l2h_regs_none_reg_none_fld_ext_r(l2h_regs_none_reg_none_fld_ext_r),
    .l2h_regs_none_reg_none_fld_int_r(l2h_regs_none_reg_none_fld_int_r),
    .l2h_regs_none_reg_int_fld_none_r(l2h_regs_none_reg_int_fld_none_r),
    .l2h_regs_none_reg_int_fld_gen_r(l2h_regs_none_reg_int_fld_gen_r),
    .l2h_regs_none_reg_int_fld_ext_r(l2h_regs_none_reg_int_fld_ext_r),
    .l2h_regs_none_reg_int_fld_int_r(l2h_regs_none_reg_int_fld_int_r),
    .l2h_regs_ext_reg_none_fld_none_r(l2h_regs_ext_reg_none_fld_none_r),
    .l2h_regs_ext_reg_none_fld_gen_r(l2h_regs_ext_reg_none_fld_gen_r),
    .l2h_regs_ext_reg_none_fld_ext_r(l2h_regs_ext_reg_none_fld_ext_r),
    .l2h_regs_ext_reg_none_fld_int_r(l2h_regs_ext_reg_none_fld_int_r),
    .l2h_regs_ext_reg_int_fld_none_r(l2h_regs_ext_reg_int_fld_none_r),
    .l2h_regs_ext_reg_int_fld_gen_r(l2h_regs_ext_reg_int_fld_gen_r),
    .l2h_regs_ext_reg_int_fld_ext_r(l2h_regs_ext_reg_int_fld_ext_r),
    .l2h_regs_ext_reg_int_fld_int_r(l2h_regs_ext_reg_int_fld_int_r),
    .l2h_wrap_info_reg_bar1_r(l2h_wrap_info_reg_bar1_r),
    .l2h_wrap_info_reg_bar2_r(l2h_wrap_info_reg_bar2_r),
    .l2h_wrap_info_reg_bar3_r(l2h_wrap_info_reg_bar3_r) );
    
endmodule


//---------- module ordt_wrap_sync_stages
module ordt_wrap_sync_stages
( clk, in_sig, out_sig );
  parameter STAGES = 1;
  parameter WIDTH = 1;
  input    clk;
  input     [WIDTH-1:0] in_sig;
  output    [WIDTH-1:0] out_sig;
  reg   [WIDTH-1:0] dly [STAGES:0];
  integer idx;
  always @ (*)
    dly[0] = in_sig;
  always @ (posedge clk) begin
    for (idx = 1; idx <= STAGES; idx=idx+1)
        dly[idx] <= #1 dly[idx-1];
  end
  assign out_sig = dly[STAGES];
endmodule
//
//---------- module top_pio_iwrap
//
module top_pio_iwrap
(
  clk,
  reset,
  h2l_regs_none_reg_none_fld_none_w,
  h2l_regs_none_reg_none_fld_none_we,
  h2l_regs_none_reg_none_fld_gen_w,
  h2l_regs_none_reg_none_fld_gen_we,
  h2l_regs_none_reg_none_fld_ext_w,
  h2l_regs_none_reg_none_fld_ext_we,
  h2l_regs_none_reg_none_fld_int_w,
  h2l_regs_none_reg_none_fld_int_we,
  h2l_regs_none_reg_int_fld_none_w,
  h2l_regs_none_reg_int_fld_none_we,
  h2l_regs_none_reg_int_fld_gen_w,
  h2l_regs_none_reg_int_fld_gen_we,
  h2l_regs_none_reg_int_fld_ext_w,
  h2l_regs_none_reg_int_fld_ext_we,
  h2l_regs_none_reg_int_fld_int_w,
  h2l_regs_none_reg_int_fld_int_we,
  h2l_regs_ext_reg_none_fld_none_w,
  h2l_regs_ext_reg_none_fld_none_we,
  h2l_regs_ext_reg_none_fld_gen_w,
  h2l_regs_ext_reg_none_fld_gen_we,
  h2l_regs_ext_reg_none_fld_ext_w,
  h2l_regs_ext_reg_none_fld_ext_we,
  h2l_regs_ext_reg_none_fld_int_w,
  h2l_regs_ext_reg_none_fld_int_we,
  h2l_regs_ext_reg_int_fld_none_w,
  h2l_regs_ext_reg_int_fld_none_we,
  h2l_regs_ext_reg_int_fld_gen_w,
  h2l_regs_ext_reg_int_fld_gen_we,
  h2l_regs_ext_reg_int_fld_ext_w,
  h2l_regs_ext_reg_int_fld_ext_we,
  h2l_regs_ext_reg_int_fld_int_w,
  h2l_regs_ext_reg_int_fld_int_we,
  leaf_dec_wr_data,
  leaf_dec_addr,
  leaf_dec_block_sel,
  leaf_dec_valid,
  leaf_dec_wr_dvld,
  leaf_dec_cycle,
  leaf_dec_wr_width,
  newClk,

  l2h_regs_none_reg_none_fld_none_r,
  l2h_regs_none_reg_none_fld_gen_r,
  l2h_regs_none_reg_none_fld_ext_r,
  l2h_regs_none_reg_none_fld_int_r,
  l2h_regs_none_reg_int_fld_none_r,
  l2h_regs_none_reg_int_fld_gen_r,
  l2h_regs_none_reg_int_fld_ext_r,
  l2h_regs_none_reg_int_fld_int_r,
  l2h_regs_ext_reg_none_fld_none_r,
  l2h_regs_ext_reg_none_fld_gen_r,
  l2h_regs_ext_reg_none_fld_ext_r,
  l2h_regs_ext_reg_none_fld_int_r,
  l2h_regs_ext_reg_int_fld_none_r,
  l2h_regs_ext_reg_int_fld_gen_r,
  l2h_regs_ext_reg_int_fld_ext_r,
  l2h_regs_ext_reg_int_fld_int_r,
  l2h_wrap_info_reg_bar1_r,
  l2h_wrap_info_reg_bar2_r,
  l2h_wrap_info_reg_bar3_r,
  dec_leaf_rd_data,
  dec_leaf_ack,
  dec_leaf_nack,
  dec_leaf_accept,
  dec_leaf_reject,
  dec_leaf_retry_atomic,
  dec_leaf_data_width );

  //------- inputs
  input    clk;
  input    reset;
  input    h2l_regs_none_reg_none_fld_none_w;
  input    h2l_regs_none_reg_none_fld_none_we;
  input    h2l_regs_none_reg_none_fld_gen_w;
  input    h2l_regs_none_reg_none_fld_gen_we;
  input    h2l_regs_none_reg_none_fld_ext_w;
  input    h2l_regs_none_reg_none_fld_ext_we;
  input    h2l_regs_none_reg_none_fld_int_w;
  input    h2l_regs_none_reg_none_fld_int_we;
  input    h2l_regs_none_reg_int_fld_none_w;
  input    h2l_regs_none_reg_int_fld_none_we;
  input    h2l_regs_none_reg_int_fld_gen_w;
  input    h2l_regs_none_reg_int_fld_gen_we;
  input    h2l_regs_none_reg_int_fld_ext_w;
  input    h2l_regs_none_reg_int_fld_ext_we;
  input    h2l_regs_none_reg_int_fld_int_w;
  input    h2l_regs_none_reg_int_fld_int_we;
  input    h2l_regs_ext_reg_none_fld_none_w;
  input    h2l_regs_ext_reg_none_fld_none_we;
  input    h2l_regs_ext_reg_none_fld_gen_w;
  input    h2l_regs_ext_reg_none_fld_gen_we;
  input    h2l_regs_ext_reg_none_fld_ext_w;
  input    h2l_regs_ext_reg_none_fld_ext_we;
  input    h2l_regs_ext_reg_none_fld_int_w;
  input    h2l_regs_ext_reg_none_fld_int_we;
  input    h2l_regs_ext_reg_int_fld_none_w;
  input    h2l_regs_ext_reg_int_fld_none_we;
  input    h2l_regs_ext_reg_int_fld_gen_w;
  input    h2l_regs_ext_reg_int_fld_gen_we;
  input    h2l_regs_ext_reg_int_fld_ext_w;
  input    h2l_regs_ext_reg_int_fld_ext_we;
  input    h2l_regs_ext_reg_int_fld_int_w;
  input    h2l_regs_ext_reg_int_fld_int_we;
  input     [31:0] leaf_dec_wr_data;
  input     [39:0] leaf_dec_addr;
  input    leaf_dec_block_sel;
  input    leaf_dec_valid;
  input    leaf_dec_wr_dvld;
  input     [1:0] leaf_dec_cycle;
  input     [2:0] leaf_dec_wr_width;
  input    newClk;

  //------- outputs
  output    l2h_regs_none_reg_none_fld_none_r;
  output    l2h_regs_none_reg_none_fld_gen_r;
  output    l2h_regs_none_reg_none_fld_ext_r;
  output    l2h_regs_none_reg_none_fld_int_r;
  output    l2h_regs_none_reg_int_fld_none_r;
  output    l2h_regs_none_reg_int_fld_gen_r;
  output    l2h_regs_none_reg_int_fld_ext_r;
  output    l2h_regs_none_reg_int_fld_int_r;
  output    l2h_regs_ext_reg_none_fld_none_r;
  output    l2h_regs_ext_reg_none_fld_gen_r;
  output    l2h_regs_ext_reg_none_fld_ext_r;
  output    l2h_regs_ext_reg_none_fld_int_r;
  output    l2h_regs_ext_reg_int_fld_none_r;
  output    l2h_regs_ext_reg_int_fld_gen_r;
  output    l2h_regs_ext_reg_int_fld_ext_r;
  output    l2h_regs_ext_reg_int_fld_int_r;
  output    l2h_wrap_info_reg_bar1_r;
  output    l2h_wrap_info_reg_bar2_r;
  output    l2h_wrap_info_reg_bar3_r;
  output     [31:0] dec_leaf_rd_data;
  output    dec_leaf_ack;
  output    dec_leaf_nack;
  output    dec_leaf_accept;
  output    dec_leaf_reject;
  output    dec_leaf_retry_atomic;
  output     [2:0] dec_leaf_data_width;


  //------- wire defines
  wire  l2h_regs_none_reg_none_fld_none_r;
  wire  l2h_regs_none_reg_none_fld_gen_r;
  wire  l2h_regs_none_reg_none_fld_ext_r;
  wire  l2h_regs_none_reg_none_fld_int_r;
  wire  l2h_regs_none_reg_int_fld_none_r;
  wire  l2h_regs_none_reg_int_fld_gen_r;
  wire  l2h_regs_none_reg_int_fld_ext_r;
  wire  l2h_regs_none_reg_int_fld_int_r;
  wire  l2h_regs_ext_reg_none_fld_none_r;
  wire  l2h_regs_ext_reg_none_fld_gen_r;
  wire  l2h_regs_ext_reg_none_fld_ext_r;
  wire  l2h_regs_ext_reg_none_fld_int_r;
  wire  l2h_regs_ext_reg_int_fld_none_r;
  wire  l2h_regs_ext_reg_int_fld_gen_r;
  wire  l2h_regs_ext_reg_int_fld_ext_r;
  wire  l2h_regs_ext_reg_int_fld_int_r;
  wire  l2h_wrap_info_reg_bar1_r;
  wire  l2h_wrap_info_reg_bar2_r;
  wire  l2h_wrap_info_reg_bar3_r;
  wire   [31:0] dec_leaf_rd_data;
  wire  dec_leaf_ack;
  wire  dec_leaf_nack;
  wire  dec_leaf_accept;
  wire  dec_leaf_reject;
  wire  dec_leaf_retry_atomic;
  wire   [2:0] dec_leaf_data_width;
  wire  inst_pio_clk;
  wire  inst_pio_reset;
  wire  inst_pio_h2l_regs_none_reg_none_fld_none_w;
  wire  inst_pio_h2l_regs_none_reg_none_fld_none_we;
  wire  inst_pio_h2l_regs_none_reg_none_fld_gen_w;
  wire  inst_pio_h2l_regs_none_reg_none_fld_gen_we;
  wire  inst_pio_h2l_regs_none_reg_none_fld_ext_w;
  wire  inst_pio_h2l_regs_none_reg_none_fld_ext_we;
  wire  inst_pio_h2l_regs_none_reg_none_fld_int_w;
  wire  inst_pio_h2l_regs_none_reg_none_fld_int_we;
  wire  inst_pio_h2l_regs_none_reg_int_fld_none_w;
  wire  inst_pio_h2l_regs_none_reg_int_fld_none_we;
  wire  inst_pio_h2l_regs_none_reg_int_fld_gen_w;
  wire  inst_pio_h2l_regs_none_reg_int_fld_gen_we;
  wire  inst_pio_h2l_regs_none_reg_int_fld_ext_w;
  wire  inst_pio_h2l_regs_none_reg_int_fld_ext_we;
  wire  inst_pio_h2l_regs_none_reg_int_fld_int_w;
  wire  inst_pio_h2l_regs_none_reg_int_fld_int_we;
  wire  inst_pio_h2l_regs_ext_reg_none_fld_none_w;
  wire  inst_pio_h2l_regs_ext_reg_none_fld_none_we;
  wire  inst_pio_h2l_regs_ext_reg_none_fld_gen_w;
  wire  inst_pio_h2l_regs_ext_reg_none_fld_gen_we;
  wire  inst_pio_h2l_regs_ext_reg_none_fld_ext_w;
  wire  inst_pio_h2l_regs_ext_reg_none_fld_ext_we;
  wire  inst_pio_h2l_regs_ext_reg_none_fld_int_w;
  wire  inst_pio_h2l_regs_ext_reg_none_fld_int_we;
  wire  inst_pio_h2l_regs_ext_reg_int_fld_none_w;
  wire  inst_pio_h2l_regs_ext_reg_int_fld_none_we;
  wire  inst_pio_h2l_regs_ext_reg_int_fld_gen_w;
  wire  inst_pio_h2l_regs_ext_reg_int_fld_gen_we;
  wire  inst_pio_h2l_regs_ext_reg_int_fld_ext_w;
  wire  inst_pio_h2l_regs_ext_reg_int_fld_ext_we;
  wire  inst_pio_h2l_regs_ext_reg_int_fld_int_w;
  wire  inst_pio_h2l_regs_ext_reg_int_fld_int_we;
  wire   [31:0] inst_pio_leaf_dec_wr_data;
  wire   [39:0] inst_pio_leaf_dec_addr;
  wire  inst_pio_leaf_dec_block_sel;
  wire  inst_pio_leaf_dec_valid;
  wire  inst_pio_leaf_dec_wr_dvld;
  wire   [1:0] inst_pio_leaf_dec_cycle;
  wire   [2:0] inst_pio_leaf_dec_wr_width;
  wire  inst_pio_l2h_regs_none_reg_none_fld_none_r;
  wire  inst_pio_l2h_regs_none_reg_none_fld_gen_r;
  wire  inst_pio_l2h_regs_none_reg_none_fld_ext_r;
  wire  inst_pio_l2h_regs_none_reg_none_fld_int_r;
  wire  inst_pio_l2h_regs_none_reg_int_fld_none_r;
  wire  inst_pio_l2h_regs_none_reg_int_fld_gen_r;
  wire  inst_pio_l2h_regs_none_reg_int_fld_ext_r;
  wire  inst_pio_l2h_regs_none_reg_int_fld_int_r;
  wire  inst_pio_l2h_regs_ext_reg_none_fld_none_r;
  wire  inst_pio_l2h_regs_ext_reg_none_fld_gen_r;
  wire  inst_pio_l2h_regs_ext_reg_none_fld_ext_r;
  wire  inst_pio_l2h_regs_ext_reg_none_fld_int_r;
  wire  inst_pio_l2h_regs_ext_reg_int_fld_none_r;
  wire  inst_pio_l2h_regs_ext_reg_int_fld_gen_r;
  wire  inst_pio_l2h_regs_ext_reg_int_fld_ext_r;
  wire  inst_pio_l2h_regs_ext_reg_int_fld_int_r;
  wire  inst_pio_l2h_wrap_info_reg_bar1_r;
  wire  inst_pio_l2h_wrap_info_reg_bar2_r;
  wire  inst_pio_l2h_wrap_info_reg_bar3_r;
  wire   [31:0] inst_pio_dec_leaf_rd_data;
  wire  inst_pio_dec_leaf_ack;
  wire  inst_pio_dec_leaf_nack;
  wire  inst_pio_dec_leaf_accept;
  wire  inst_pio_dec_leaf_reject;
  wire  inst_pio_dec_leaf_retry_atomic;
  wire   [2:0] inst_pio_dec_leaf_data_width;
  
  ordt_wrap_sync_stages #(.STAGES(2), .WIDTH(1)) sync_delay_0 (newClk, inst_pio_l2h_wrap_info_reg_bar3_r, l2h_wrap_info_reg_bar3_r);
  
  //------- assigns
  assign  inst_pio_clk = clk;
  assign  inst_pio_reset = reset;
  assign  inst_pio_h2l_regs_none_reg_none_fld_none_w = h2l_regs_none_reg_none_fld_none_w;
  assign  inst_pio_h2l_regs_none_reg_none_fld_none_we = h2l_regs_none_reg_none_fld_none_we;
  assign  inst_pio_h2l_regs_none_reg_none_fld_gen_w = h2l_regs_none_reg_none_fld_gen_w;
  assign  inst_pio_h2l_regs_none_reg_none_fld_gen_we = h2l_regs_none_reg_none_fld_gen_we;
  assign  inst_pio_h2l_regs_none_reg_none_fld_ext_w = h2l_regs_none_reg_none_fld_ext_w;
  assign  inst_pio_h2l_regs_none_reg_none_fld_ext_we = h2l_regs_none_reg_none_fld_ext_we;
  assign  inst_pio_h2l_regs_none_reg_none_fld_int_w = h2l_regs_none_reg_none_fld_int_w;
  assign  inst_pio_h2l_regs_none_reg_none_fld_int_we = h2l_regs_none_reg_none_fld_int_we;
  assign  inst_pio_h2l_regs_none_reg_int_fld_none_w = h2l_regs_none_reg_int_fld_none_w;
  assign  inst_pio_h2l_regs_none_reg_int_fld_none_we = h2l_regs_none_reg_int_fld_none_we;
  assign  inst_pio_h2l_regs_none_reg_int_fld_gen_w = h2l_regs_none_reg_int_fld_gen_w;
  assign  inst_pio_h2l_regs_none_reg_int_fld_gen_we = h2l_regs_none_reg_int_fld_gen_we;
  assign  inst_pio_h2l_regs_none_reg_int_fld_ext_w = h2l_regs_none_reg_int_fld_ext_w;
  assign  inst_pio_h2l_regs_none_reg_int_fld_ext_we = h2l_regs_none_reg_int_fld_ext_we;
  assign  inst_pio_h2l_regs_none_reg_int_fld_int_w = h2l_regs_none_reg_int_fld_int_w;
  assign  inst_pio_h2l_regs_none_reg_int_fld_int_we = h2l_regs_none_reg_int_fld_int_we;
  assign  inst_pio_h2l_regs_ext_reg_none_fld_none_w = h2l_regs_ext_reg_none_fld_none_w;
  assign  inst_pio_h2l_regs_ext_reg_none_fld_none_we = h2l_regs_ext_reg_none_fld_none_we;
  assign  inst_pio_h2l_regs_ext_reg_none_fld_gen_w = h2l_regs_ext_reg_none_fld_gen_w;
  assign  inst_pio_h2l_regs_ext_reg_none_fld_gen_we = h2l_regs_ext_reg_none_fld_gen_we;
  assign  inst_pio_h2l_regs_ext_reg_none_fld_ext_w = h2l_regs_ext_reg_none_fld_ext_w;
  assign  inst_pio_h2l_regs_ext_reg_none_fld_ext_we = h2l_regs_ext_reg_none_fld_ext_we;
  assign  inst_pio_h2l_regs_ext_reg_none_fld_int_w = h2l_regs_ext_reg_none_fld_int_w;
  assign  inst_pio_h2l_regs_ext_reg_none_fld_int_we = h2l_regs_ext_reg_none_fld_int_we;
  assign  inst_pio_h2l_regs_ext_reg_int_fld_none_w = h2l_regs_ext_reg_int_fld_none_w;
  assign  inst_pio_h2l_regs_ext_reg_int_fld_none_we = h2l_regs_ext_reg_int_fld_none_we;
  assign  inst_pio_h2l_regs_ext_reg_int_fld_gen_w = h2l_regs_ext_reg_int_fld_gen_w;
  assign  inst_pio_h2l_regs_ext_reg_int_fld_gen_we = h2l_regs_ext_reg_int_fld_gen_we;
  assign  inst_pio_h2l_regs_ext_reg_int_fld_ext_w = h2l_regs_ext_reg_int_fld_ext_w;
  assign  inst_pio_h2l_regs_ext_reg_int_fld_ext_we = h2l_regs_ext_reg_int_fld_ext_we;
  assign  inst_pio_h2l_regs_ext_reg_int_fld_int_w = h2l_regs_ext_reg_int_fld_int_w;
  assign  inst_pio_h2l_regs_ext_reg_int_fld_int_we = h2l_regs_ext_reg_int_fld_int_we;
  assign  inst_pio_leaf_dec_wr_data = leaf_dec_wr_data;
  assign  inst_pio_leaf_dec_addr = leaf_dec_addr;
  assign  inst_pio_leaf_dec_block_sel = leaf_dec_block_sel;
  assign  inst_pio_leaf_dec_valid = leaf_dec_valid;
  assign  inst_pio_leaf_dec_wr_dvld = leaf_dec_wr_dvld;
  assign  inst_pio_leaf_dec_cycle = leaf_dec_cycle;
  assign  inst_pio_leaf_dec_wr_width = leaf_dec_wr_width;
  assign  l2h_regs_none_reg_none_fld_none_r = inst_pio_l2h_regs_none_reg_none_fld_none_r;
  assign  l2h_regs_none_reg_none_fld_gen_r = inst_pio_l2h_regs_none_reg_none_fld_gen_r;
  assign  l2h_regs_none_reg_none_fld_ext_r = inst_pio_l2h_regs_none_reg_none_fld_ext_r;
  assign  l2h_regs_none_reg_none_fld_int_r = inst_pio_l2h_regs_none_reg_none_fld_int_r;
  assign  l2h_regs_none_reg_int_fld_none_r = inst_pio_l2h_regs_none_reg_int_fld_none_r;
  assign  l2h_regs_none_reg_int_fld_gen_r = inst_pio_l2h_regs_none_reg_int_fld_gen_r;
  assign  l2h_regs_none_reg_int_fld_ext_r = inst_pio_l2h_regs_none_reg_int_fld_ext_r;
  assign  l2h_regs_none_reg_int_fld_int_r = inst_pio_l2h_regs_none_reg_int_fld_int_r;
  assign  l2h_regs_ext_reg_none_fld_none_r = inst_pio_l2h_regs_ext_reg_none_fld_none_r;
  assign  l2h_regs_ext_reg_none_fld_gen_r = inst_pio_l2h_regs_ext_reg_none_fld_gen_r;
  assign  l2h_regs_ext_reg_none_fld_ext_r = inst_pio_l2h_regs_ext_reg_none_fld_ext_r;
  assign  l2h_regs_ext_reg_none_fld_int_r = inst_pio_l2h_regs_ext_reg_none_fld_int_r;
  assign  l2h_regs_ext_reg_int_fld_none_r = inst_pio_l2h_regs_ext_reg_int_fld_none_r;
  assign  l2h_regs_ext_reg_int_fld_gen_r = inst_pio_l2h_regs_ext_reg_int_fld_gen_r;
  assign  l2h_regs_ext_reg_int_fld_ext_r = inst_pio_l2h_regs_ext_reg_int_fld_ext_r;
  assign  l2h_regs_ext_reg_int_fld_int_r = inst_pio_l2h_regs_ext_reg_int_fld_int_r;
  assign  l2h_wrap_info_reg_bar1_r = inst_pio_l2h_wrap_info_reg_bar1_r;
  assign  l2h_wrap_info_reg_bar2_r = ~inst_pio_l2h_wrap_info_reg_bar2_r;
  assign  dec_leaf_rd_data = inst_pio_dec_leaf_rd_data;
  assign  dec_leaf_ack = inst_pio_dec_leaf_ack;
  assign  dec_leaf_nack = inst_pio_dec_leaf_nack;
  assign  dec_leaf_accept = inst_pio_dec_leaf_accept;
  assign  dec_leaf_reject = inst_pio_dec_leaf_reject;
  assign  dec_leaf_retry_atomic = inst_pio_dec_leaf_retry_atomic;
  assign  dec_leaf_data_width = inst_pio_dec_leaf_data_width;
  
  top_pio pio (
    .clk(inst_pio_clk),
    .reset(inst_pio_reset),
    .h2l_regs_none_reg_none_fld_none_w(inst_pio_h2l_regs_none_reg_none_fld_none_w),
    .h2l_regs_none_reg_none_fld_none_we(inst_pio_h2l_regs_none_reg_none_fld_none_we),
    .h2l_regs_none_reg_none_fld_gen_w(inst_pio_h2l_regs_none_reg_none_fld_gen_w),
    .h2l_regs_none_reg_none_fld_gen_we(inst_pio_h2l_regs_none_reg_none_fld_gen_we),
    .h2l_regs_none_reg_none_fld_ext_w(inst_pio_h2l_regs_none_reg_none_fld_ext_w),
    .h2l_regs_none_reg_none_fld_ext_we(inst_pio_h2l_regs_none_reg_none_fld_ext_we),
    .h2l_regs_none_reg_none_fld_int_w(inst_pio_h2l_regs_none_reg_none_fld_int_w),
    .h2l_regs_none_reg_none_fld_int_we(inst_pio_h2l_regs_none_reg_none_fld_int_we),
    .h2l_regs_none_reg_int_fld_none_w(inst_pio_h2l_regs_none_reg_int_fld_none_w),
    .h2l_regs_none_reg_int_fld_none_we(inst_pio_h2l_regs_none_reg_int_fld_none_we),
    .h2l_regs_none_reg_int_fld_gen_w(inst_pio_h2l_regs_none_reg_int_fld_gen_w),
    .h2l_regs_none_reg_int_fld_gen_we(inst_pio_h2l_regs_none_reg_int_fld_gen_we),
    .h2l_regs_none_reg_int_fld_ext_w(inst_pio_h2l_regs_none_reg_int_fld_ext_w),
    .h2l_regs_none_reg_int_fld_ext_we(inst_pio_h2l_regs_none_reg_int_fld_ext_we),
    .h2l_regs_none_reg_int_fld_int_w(inst_pio_h2l_regs_none_reg_int_fld_int_w),
    .h2l_regs_none_reg_int_fld_int_we(inst_pio_h2l_regs_none_reg_int_fld_int_we),
    .h2l_regs_ext_reg_none_fld_none_w(inst_pio_h2l_regs_ext_reg_none_fld_none_w),
    .h2l_regs_ext_reg_none_fld_none_we(inst_pio_h2l_regs_ext_reg_none_fld_none_we),
    .h2l_regs_ext_reg_none_fld_gen_w(inst_pio_h2l_regs_ext_reg_none_fld_gen_w),
    .h2l_regs_ext_reg_none_fld_gen_we(inst_pio_h2l_regs_ext_reg_none_fld_gen_we),
    .h2l_regs_ext_reg_none_fld_ext_w(inst_pio_h2l_regs_ext_reg_none_fld_ext_w),
    .h2l_regs_ext_reg_none_fld_ext_we(inst_pio_h2l_regs_ext_reg_none_fld_ext_we),
    .h2l_regs_ext_reg_none_fld_int_w(inst_pio_h2l_regs_ext_reg_none_fld_int_w),
    .h2l_regs_ext_reg_none_fld_int_we(inst_pio_h2l_regs_ext_reg_none_fld_int_we),
    .h2l_regs_ext_reg_int_fld_none_w(inst_pio_h2l_regs_ext_reg_int_fld_none_w),
    .h2l_regs_ext_reg_int_fld_none_we(inst_pio_h2l_regs_ext_reg_int_fld_none_we),
    .h2l_regs_ext_reg_int_fld_gen_w(inst_pio_h2l_regs_ext_reg_int_fld_gen_w),
    .h2l_regs_ext_reg_int_fld_gen_we(inst_pio_h2l_regs_ext_reg_int_fld_gen_we),
    .h2l_regs_ext_reg_int_fld_ext_w(inst_pio_h2l_regs_ext_reg_int_fld_ext_w),
    .h2l_regs_ext_reg_int_fld_ext_we(inst_pio_h2l_regs_ext_reg_int_fld_ext_we),
    .h2l_regs_ext_reg_int_fld_int_w(inst_pio_h2l_regs_ext_reg_int_fld_int_w),
    .h2l_regs_ext_reg_int_fld_int_we(inst_pio_h2l_regs_ext_reg_int_fld_int_we),
    .leaf_dec_wr_data(inst_pio_leaf_dec_wr_data),
    .leaf_dec_addr(inst_pio_leaf_dec_addr),
    .leaf_dec_block_sel(inst_pio_leaf_dec_block_sel),
    .leaf_dec_valid(inst_pio_leaf_dec_valid),
    .leaf_dec_wr_dvld(inst_pio_leaf_dec_wr_dvld),
    .leaf_dec_cycle(inst_pio_leaf_dec_cycle),
    .leaf_dec_wr_width(inst_pio_leaf_dec_wr_width),
    .l2h_regs_none_reg_none_fld_none_r(inst_pio_l2h_regs_none_reg_none_fld_none_r),
    .l2h_regs_none_reg_none_fld_gen_r(inst_pio_l2h_regs_none_reg_none_fld_gen_r),
    .l2h_regs_none_reg_none_fld_ext_r(inst_pio_l2h_regs_none_reg_none_fld_ext_r),
    .l2h_regs_none_reg_none_fld_int_r(inst_pio_l2h_regs_none_reg_none_fld_int_r),
    .l2h_regs_none_reg_int_fld_none_r(inst_pio_l2h_regs_none_reg_int_fld_none_r),
    .l2h_regs_none_reg_int_fld_gen_r(inst_pio_l2h_regs_none_reg_int_fld_gen_r),
    .l2h_regs_none_reg_int_fld_ext_r(inst_pio_l2h_regs_none_reg_int_fld_ext_r),
    .l2h_regs_none_reg_int_fld_int_r(inst_pio_l2h_regs_none_reg_int_fld_int_r),
    .l2h_regs_ext_reg_none_fld_none_r(inst_pio_l2h_regs_ext_reg_none_fld_none_r),
    .l2h_regs_ext_reg_none_fld_gen_r(inst_pio_l2h_regs_ext_reg_none_fld_gen_r),
    .l2h_regs_ext_reg_none_fld_ext_r(inst_pio_l2h_regs_ext_reg_none_fld_ext_r),
    .l2h_regs_ext_reg_none_fld_int_r(inst_pio_l2h_regs_ext_reg_none_fld_int_r),
    .l2h_regs_ext_reg_int_fld_none_r(inst_pio_l2h_regs_ext_reg_int_fld_none_r),
    .l2h_regs_ext_reg_int_fld_gen_r(inst_pio_l2h_regs_ext_reg_int_fld_gen_r),
    .l2h_regs_ext_reg_int_fld_ext_r(inst_pio_l2h_regs_ext_reg_int_fld_ext_r),
    .l2h_regs_ext_reg_int_fld_int_r(inst_pio_l2h_regs_ext_reg_int_fld_int_r),
    .l2h_wrap_info_reg_bar1_r(inst_pio_l2h_wrap_info_reg_bar1_r),
    .l2h_wrap_info_reg_bar2_r(inst_pio_l2h_wrap_info_reg_bar2_r),
    .l2h_wrap_info_reg_bar3_r(inst_pio_l2h_wrap_info_reg_bar3_r),
    .dec_leaf_rd_data(inst_pio_dec_leaf_rd_data),
    .dec_leaf_ack(inst_pio_dec_leaf_ack),
    .dec_leaf_nack(inst_pio_dec_leaf_nack),
    .dec_leaf_accept(inst_pio_dec_leaf_accept),
    .dec_leaf_reject(inst_pio_dec_leaf_reject),
    .dec_leaf_retry_atomic(inst_pio_dec_leaf_retry_atomic),
    .dec_leaf_data_width(inst_pio_dec_leaf_data_width) );
    
endmodule

