/*   Ordt 170413.03 autogenerated file 
 *   Input: ./rdl_iwrap/test.rdl
 *   Parms: ./rdl_iwrap/test.parms
 *   Date: Thu Apr 13 23:28:53 EDT 2017
 */

register_set top "Registers for top" {

  address = 0x0;
  register_width = 32;
  register_set regs_none "regs_none register_set" {
    address = 0x0;
    
    register reg_none "reg_none register" {
      address = 0x0;
      nop[28];
      integer fld_int[1] "fld_int field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
      integer fld_ext[1] "fld_ext field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
      integer fld_gen[1] "fld_gen field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
      integer fld_none[1] "fld_none field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
    };
    
    register reg_int "reg_int register" {
      address = 0x4;
      nop[28];
      integer fld_int[1] "fld_int field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
      integer fld_ext[1] "fld_ext field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
      integer fld_gen[1] "fld_gen field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
      integer fld_none[1] "fld_none field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
    };
    
    register_set_size = 0x8;
  };
  
  register_set regs_ext "regs_ext register_set" {
    address = 0x8;
    
    register reg_none "reg_none register" {
      address = 0x0;
      nop[28];
      integer fld_int[1] "fld_int field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
      integer fld_ext[1] "fld_ext field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
      integer fld_gen[1] "fld_gen field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
      integer fld_none[1] "fld_none field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
    };
    
    register reg_int "reg_int register" {
      address = 0x4;
      nop[28];
      integer fld_int[1] "fld_int field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
      integer fld_ext[1] "fld_ext field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
      integer fld_gen[1] "fld_gen field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
      integer fld_none[1] "fld_none field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
    };
    
    register_set_size = 0x8;
  };
  
  register_set_size = 0x10;
};

