//   Ordt 230719.01 autogenerated file 
//   Input: ./rdl_write_enable/test.rdl
//   Parms: ./rdl_write_enable/test.parms
//   Date: Thu Jul 20 13:47:02 EDT 2023
//

#ifndef __FOO_REGISTER_MAP__
#define __FOO_REGISTER_MAP__

#include <bits.h>

/* FOO_REGISTERS memory map */
enum FOO_REGS {
  INTR_REG = 0x0,
  LOG_REG = 0x4,
  BIGREG = 0x8,
  CHILDMAP_32B_ARRAY_REG_0 = 0x100,
  CHILDMAP_32B_ARRAY_REG_1 = 0x104,
  CHILDMAP_32B_ARRAY_REG_2 = 0x108,
  CHILDMAP_32B_ARRAY_REG_3 = 0x10c,
  CHILDMAP_32B_ARRAY_REG_4 = 0x110,
  CHILDMAP_32B_ARRAY_REG_5 = 0x114,
  CHILDMAP_32B_ARRAY_REG_6 = 0x118,
  CHILDMAP_32B_ARRAY_REG_7 = 0x11c
};

/* INTR_REG register fields */
#define INTR_REG_COUNT_FLD GENMASK(7, 0)
#define INTR_REG_INTR1 BIT(8)
#define INTR_REG_INTR2 BIT(9)

/* LOG_REG register fields */
#define LOG_REG_LOG_ERR GENMASK(7, 0)
#define LOG_REG_LOG_VALUE GENMASK(15, 8)

/* BIGREG register fields */
#define BIGREG_FIELD64 GENMASK(63, 0)

/* CHILDMAP_32B_ARRAY_REG_0 register fields */
#define CHILDMAP_32B_ARRAY_REG_0_FIELD32 GENMASK(31, 0)

/* CHILDMAP_32B_ARRAY_REG_1 register fields */
#define CHILDMAP_32B_ARRAY_REG_1_FIELD32 GENMASK(31, 0)

/* CHILDMAP_32B_ARRAY_REG_2 register fields */
#define CHILDMAP_32B_ARRAY_REG_2_FIELD32 GENMASK(31, 0)

/* CHILDMAP_32B_ARRAY_REG_3 register fields */
#define CHILDMAP_32B_ARRAY_REG_3_FIELD32 GENMASK(31, 0)

/* CHILDMAP_32B_ARRAY_REG_4 register fields */
#define CHILDMAP_32B_ARRAY_REG_4_FIELD32 GENMASK(31, 0)

/* CHILDMAP_32B_ARRAY_REG_5 register fields */
#define CHILDMAP_32B_ARRAY_REG_5_FIELD32 GENMASK(31, 0)

/* CHILDMAP_32B_ARRAY_REG_6 register fields */
#define CHILDMAP_32B_ARRAY_REG_6_FIELD32 GENMASK(31, 0)

/* CHILDMAP_32B_ARRAY_REG_7 register fields */
#define CHILDMAP_32B_ARRAY_REG_7_FIELD32 GENMASK(31, 0)

#endif
