/*   Ordt 180327.01 autogenerated file 
 *   Input: ./rdl_write_enable/test.rdl
 *   Parms: ./rdl_write_enable/test.parms
 *   Date: Tue Mar 27 14:56:17 EDT 2018
 */

register_set foo "Registers for foo" {

  address = 0x0;
  register_width = 32;
  register intr_reg "intr_reg register" {
    address = 0x0;
    nop[22];
    integer intr2[1] "intr2 field" param {
      access_mode = READ_WRITE;
      reset = 0x0;
    };
    integer intr1[1] "intr1 field" param {
      access_mode = READ_WRITE;
      reset = 0x0;
    };
    integer count_fld[8] "count_fld field" param {
      access_mode = READ_WRITE;
      reset = 0x55;
    };
  };
  
  register log_reg "log_reg register" {
    address = 0x4;
    category = { STATE };
    nop[16];
    integer log_value[8] "log_value field" param {
      access_mode = READ_ONLY;
      reset = 0x0;
    };
    integer log_err[8] "log_err field" param {
      access_mode = READ_WRITE;
      reset = 0x4;
    };
  };
  
  register bigreg "bigreg register" {
    address = 0x8;
    register_width = 64;
    integer field64[64] "field64 field" param {
      access_mode = READ_WRITE;
      reset = 0x0;
    };
  };
  
  register_set childmap_32b "childmap_32b register_set" {
    address = 0x100;
    
    register array_reg "array_reg register" {
      address = 0x0;
      repeat = 8;
      integer field32[32] "field32 field" param {
        access_mode = READ_WRITE;
        reset = 0x0;
      };
    };
    
    register_set_size = 0x20;
  };
  
  register_set_size = 0x120;
};

